# # 关键词列表,每个元素是一个字典,包含关键词和对应权重


# Topic = 小米汽车
xiaomi_car_keywords = [
    {'keyword': '小米汽车', 'weight': 10},
    {'keyword': 'su7', 'weight': 10},
    {'keyword': 'su 7', 'weight': 10},
    {'keyword': '小米suv', 'weight': 10},
    {'keyword': '雷军', 'weight': 9},
    {'keyword': '雷总', 'weight': 9},
    {'keyword': 'V8S超级电机', 'weight': 8},
    {'keyword': '江波龙', 'weight': 8},
]

# Topic = 低空经济
low_altitude_economy_keywords = [
    {'keyword': '低空物流', 'weight': 10},
    {'keyword': '低空经济', 'weight': 10},
    {'keyword': 'eVTOL', 'weight': 10},
    {'keyword': '低空医疗', 'weight': 10},
    {'keyword': '低空航线', 'weight': 10},
    {'keyword': '低空出行', 'weight': 10},
    {'keyword': '低小慢', 'weight': 10},
    {'keyword': '垂直起降', 'weight': 8},
    {'keyword': '空中交通', 'weight': 8},
    {'keyword': '低空飞行器', 'weight': 8},
    {'keyword': '智能飞行', 'weight': 8},
]

# Topic = 商业航天
commercial_space_keywords = [
    {'keyword': '运载火箭', 'weight': 9.5},
    {'keyword': '卫星互联网', 'weight': 9.0},
    {'keyword': '低轨', 'weight': 9.0},
    {'keyword': '星链', 'weight': 9.5},
    {'keyword': '可回收', 'weight': 8.5},
    {'keyword': '星座', 'weight': 9.0},
    {'keyword': '中国卫星通信集团', 'weight': 8},
    {'keyword': '中国卫通', 'weight': 8},
    {'keyword': '上海微小卫星', 'weight': 8},
    {'keyword': 'SMIC', 'weight': 8},
    {'keyword': '航天长峰', 'weight': 8},
    {'keyword': '长峰航天', 'weight': 8},
    {'keyword': '银河航天', 'weight': 8},
    {'keyword': '银河互联网', 'weight': 8},
    {'keyword': 'Galactic Network', 'weight': 8},
    {'keyword': '蓝箭', 'weight': 10},
    {'keyword': 'LandSpace', 'weight': 8},
    {'keyword': '星际荣耀', 'weight': 10},
    {'keyword': 'iSpace', 'weight': 8},
    {'keyword': '零壹', 'weight': 10},
    {'keyword': 'OneSpace', 'weight': 8},
    {'keyword': '中科微星', 'weight': 7},
    {'keyword': '天仪研究院', 'weight': 7},
    {'keyword': '天仪', 'weight': 7},
    {'keyword': 'Spacety', 'weight': 7},
    {'keyword': '星网', 'weight': 9},
    {'keyword': 'China Satellite Network', 'weight': 9},
    {'keyword': '鸿雁星座', 'weight': 8},
    {'keyword': '鸿雁', 'weight': 8},
    {'keyword': '虹云', 'weight': 8},
    {'keyword': '快舟', 'weight': 8},
]

# Topic = 通用价值点
common_value_keywords = [
    {'keyword': '加群', 'weight': 10},
    {'keyword': '该二维码7天内', 'weight': 10},
    {'keyword': '入群', 'weight': 10},
    {'keyword': '微信群', 'weight': 10},
    {'keyword': '交流群', 'weight': 10},
    {'keyword': '行业群', 'weight': 10},
    {'keyword': '投研群', 'weight': 10},
    # {'keyword': '作者微信', 'weight': 10},
    # {'keyword': '主理人', 'weight': 10},
    # {'keyword': '二维码', 'weight': 10},
    {'keyword': '长按', 'weight': 10},
    {'keyword': '电话会', 'weight': 10},
    {'keyword': '策略会', 'weight': 10},
    {'keyword': '业绩会', 'weight': 10},
    {'keyword': '腾讯会议', 'weight': 10},
    {'keyword': '沙龙', 'weight': 10},
    {'keyword': '讲座', 'weight': 10},
    {'keyword': '峰会', 'weight': 10},
    {'keyword': '交流会', 'weight': 10},
    {'keyword': '研讨会', 'weight': 10},
    {'keyword': '路演', 'weight': 10},
    {'keyword': '超预期', 'weight': 10},
    {'keyword': '预期差', 'weight': 10},
    {'keyword': '梳理', 'weight': 9},
    {'keyword': '产业链梳理', 'weight': 10},
    {'keyword': '测算', 'weight': 10},
    {'keyword': '上险量', 'weight': 10},
]

# Topic = 生物制造
Biomanufacturing_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    {'keyword': '合成生物', 'weight': 10},
    {'keyword': 'bio-made', 'weight': 10},
    {'keyword': '蛋白合成', 'weight': 10},
    {'keyword': '合成蛋白', 'weight': 10},
    {'keyword': '人造肉', 'weight': 10},
]

# Topic = 先锋热点
HotPoint_keywords = [
    {'keyword': 'p70', 'weight': 10},
    {'keyword': '董宇辉', 'weight': 10},
    {'keyword': '与辉同行', 'weight': 10},
    {'keyword': '人形机器人', 'weight': 10},
    {'keyword': '固态电池', 'weight': 10},
]




# Topic = 量化
quantitative_trading_keywords = [
    {'keyword': '量化', 'weight': 10},
    {'keyword': '量化交易', 'weight': 10},
    {'keyword': '算法交易', 'weight': 10},
    {'keyword': '阿尔法策略', 'weight': 9},
    {'keyword': '阿尔法', 'weight': 9},
    {'keyword': '阿尔法值', 'weight': 9},
    {'keyword': '阿尔法收益', 'weight': 9},
    {'keyword': '贝塔收益', 'weight': 7},
    {'keyword': '贝塔', 'weight': 9},
    {'keyword': 'beta', 'weight': 9},
    {'keyword': 'beta值', 'weight': 9},
    {'keyword': 'beta收益', 'weight': 7},
    {'keyword': '超额收益', 'weight': 8},
    {'keyword': '超额回报', 'weight': 8},
    {'keyword': '择时策略', 'weight': 8},
    {'keyword': '择时', 'weight': 8},
    {'keyword': 'dma策略', 'weight': 10},
    {'keyword': 'dma', 'weight': 10},
    {'keyword': 'dma交易', 'weight': 10},
    {'keyword': '高频交易', 'weight': 10},
    # {'keyword': '高频', 'weight': 9},
    {'keyword': '高频策略', 'weight': 9},
    {'keyword': '对冲策略', 'weight': 9},
    {'keyword': '量化对冲', 'weight': 10},
    {'keyword': '多空策略', 'weight': 8},
    {'keyword': '股指策略', 'weight': 8},
    {'keyword': '股票多空', 'weight': 7},
    {'keyword': 'cta', 'weight': 9},
    {'keyword': 'cta策略', 'weight': 9},
    {'keyword': '指增', 'weight': 10},
    {'keyword': 'smart beta', 'weight': 10},
    {'keyword': 'smart贝塔', 'weight': 10},
    {'keyword': 'smart β', 'weight': 10},
    {'keyword': '风格切换', 'weight': 8},
    {'keyword': 'etf套利', 'weight': 10},
    {'keyword': '宽基', 'weight': 10},
    {'keyword': '跨品种套利', 'weight': 8},
    {'keyword': '事件驱动', 'weight': 7},
    {'keyword': '事件驱动策略', 'weight': 8},
    {'keyword': '统计套利', 'weight': 9},
    {'keyword': '统计学', 'weight': 5},
    {'keyword': '统计学策略', 'weight': 7},
    {'keyword': '风格投资', 'weight': 6},
    {'keyword': '因子', 'weight': 10},
    {'keyword': '量化选股', 'weight': 8},
    {'keyword': '基本面选股', 'weight': 5},
    {'keyword': '量化择时', 'weight': 8},
    {'keyword': '蒙特卡罗模拟', 'weight': 7},
    {'keyword': '生成对抗网络', 'weight': 5},
    {'keyword': '指数增强', 'weight': 6},
    {'keyword': '动量策略', 'weight': 8},
    {'keyword': '均值回复', 'weight': 7},
    {'keyword': '均值回复策略', 'weight': 8},
    {'keyword': '基本面量化', 'weight': 8},
    {'keyword': '基本面量化策略', 'weight': 9},
    {'keyword': '技术分析策略', 'weight': 8},
    {'keyword': '市场中性', 'weight': 7},
    {'keyword': '市场中性策略', 'weight': 8},
    {'keyword': '趋向跟踪', 'weight': 7},
    {'keyword': '趋向跟踪策略', 'weight': 8},
    {'keyword': '投机策略', 'weight': 6},
    {'keyword': '指数化投资', 'weight': 5},
    {'keyword': '进化算法优化', 'weight': 7},
    {'keyword': '张量计算', 'weight': 4},
    {'keyword': '期现套利', 'weight': 9},
    {'keyword': '商品期货', 'weight': 8},
    {'keyword': '商品期货策略', 'weight': 9},
    {'keyword': '管理期货', 'weight': 7},
    {'keyword': '管理期货策略', 'weight': 8},
    {'keyword': '现金增强', 'weight': 6},
    {'keyword': '调仓策略', 'weight': 7},
    {'keyword': '回撤管理', 'weight': 9},
    {'keyword': 'drawdown管理', 'weight': 9},
    {'keyword': 'risk management', 'weight': 10},
    {'keyword': '波动率', 'weight': 9},
    {'keyword': 'volatility', 'weight': 9},
    {'keyword': '资金成本', 'weight': 8},
    {'keyword': 'funding costs', 'weight': 8},
    {'keyword': '市场冲击', 'weight': 8},
    {'keyword': '市场冲击成本', 'weight': 8},
    {'keyword': 'market impact', 'weight': 8},
    {'keyword': '交易成本', 'weight': 8},
    {'keyword': 'trading costs', 'weight': 8},
    {'keyword': 'risk preference', 'weight': 7},
    {'keyword': '冲击成本', 'weight': 7},
    {'keyword': '最大回撤', 'weight': 8},
    {'keyword': 'drawdown', 'weight': 10},
    {'keyword': '夏普', 'weight': 10},
    {'keyword': '风险收益比', 'weight': 9},
    {'keyword': '波动率曲面', 'weight': 8},
    {'keyword': '隐含波动率', 'weight': 8},
    {'keyword': 'delta', 'weight': 7},
    {'keyword': 'delta值', 'weight': 7},
    {'keyword': 'gamma', 'weight': 7},
    {'keyword': 'gamma值', 'weight': 7},
    {'keyword': 'vega', 'weight': 7},
    {'keyword': 'vega值', 'weight': 7},
    {'keyword': '投资组合', 'weight': 9},
    {'keyword': 'portfolio', 'weight': 8},
    {'keyword': '资产配置', 'weight': 8},
    {'keyword': 'asset allocation', 'weight': 8},
    {'keyword': '赎回', 'weight': 4},
    {'keyword': '赎回费', 'weight': 4},
    {'keyword': 'redemption fee', 'weight': 4},
    {'keyword': '微盘股', 'weight': 3},
    {'keyword': '微盘股票', 'weight': 3},
    {'keyword': '数字货币对冲基金', 'weight': 8},
    {'keyword': 'cta', 'weight': 9},
    {'keyword': '多空组合', 'weight': 7},
    {'keyword': '风险平价', 'weight': 8},
    {'keyword': '风险平价策略', 'weight': 9},
    {'keyword': '证券组合优化', 'weight': 9},
    {'keyword': '均值方差模型', 'weight': 8},
    {'keyword': '主动投资', 'weight': 5},
    {'keyword': '被动投资', 'weight': 5},
    {'keyword': '另类投资', 'weight': 6},
    {'keyword': '结构化产品', 'weight': 6},
    {'keyword': '期权投资组合', 'weight': 9},
    {'keyword': '市场收益率', 'weight': 9},
    {'keyword': 'market return', 'weight': 9},
    {'keyword': '市场效率', 'weight': 9},
    {'keyword': '有效市场', 'weight': 8},
    {'keyword': 'market efficiency', 'weight': 9},
    {'keyword': 'capital flow', 'weight': 8},
    {'keyword': '投资者情绪', 'weight': 6},
    {'keyword': 'sentiment', 'weight': 6},
    {'keyword': '回测', 'weight': 10},
    {'keyword': '实盘', 'weight': 10},
    {'keyword': 'strategy backtesting', 'weight': 10},
    {'keyword': '策略绩效评估', 'weight': 10},
    {'keyword': 'strategy performance evaluation', 'weight': 10},
    {'keyword': '波浪理论', 'weight': 6},
    {'keyword': '能量潮理论', 'weight': 5},
    {'keyword': '分型分析', 'weight': 6},
    {'keyword': '分型理论', 'weight': 6},
    {'keyword': '压力支撑位', 'weight': 6},
    {'keyword': '突破形态', 'weight': 7},
    {'keyword': 'sar', 'weight': 5},
    {'keyword': 'sar指标', 'weight': 6},
    {'keyword': 'atr指标', 'weight': 6},
    # {'keyword': 'atr', 'weight': 6},
    {'keyword': 'vr指标', 'weight': 5},
    # {'keyword': 'vr', 'weight': 5},
    {'keyword': 'dmi指标', 'weight': 6},
    # {'keyword': 'dmi', 'weight': 6},
    {'keyword': 'cci指标', 'weight': 6},
    # {'keyword': 'cci', 'weight': 6},
    {'keyword': 'kdj指标', 'weight': 6},
    # {'keyword': 'kdj', 'weight': 6},
    {'keyword': 'vstop指标', 'weight': 5},
    {'keyword': 'vstop', 'weight': 5},
    {'keyword': 'boll指标', 'weight': 6},
    # {'keyword': 'boll', 'weight': 6},
    {'keyword': 'rsi指标', 'weight': 7},
    # {'keyword': 'rsi', 'weight': 7},
    # {'keyword': '胜率', 'weight': 8},
    {'keyword': '索提诺比率', 'weight': 7},
    {'keyword': '贝塔系数', 'weight': 8},
    {'keyword': '阿尔法系数', 'weight': 8},
    {'keyword': '波动率曲面', 'weight': 9},
    {'keyword': '隐含波动率', 'weight': 9},
    {'keyword': '风险值', 'weight': 9},
    {'keyword': '希腊值', 'weight': 9},
    {'keyword': '套利定价', 'weight': 9},
    {'keyword': '有效市场假说', 'weight': 8},
    {'keyword': '互换', 'weight': 8},
    {'keyword': '股指期货', 'weight': 8},
    {'keyword': '赢率', 'weight': 8},
    {'keyword': '索提诺比率', 'weight': 7},
    {'keyword': 'beta值', 'weight': 8},
    {'keyword': 'alpha', 'weight': 9},
    {'keyword': '波率曲面', 'weight': 9},
    {'keyword': '希腊值', 'weight': 9},
    {'keyword': '无风险套利', 'weight': 10},
    {'keyword': '市场有效', 'weight': 9},
    {'keyword': '协整分析', 'weight': 8},
    {'keyword': '分位数跟踪', 'weight': 8},
    {'keyword': '期权定价', 'weight': 10},
    {'keyword': '套利策略', 'weight': 10},
    {'keyword': '幻方', 'weight': 10},
    {'keyword': '明汯', 'weight': 10},
    {'keyword': '灵均', 'weight': 10},
    {'keyword': '九坤', 'weight': 10},
    {'keyword': '衍复', 'weight': 10},
    {'keyword': '天演', 'weight': 10},
    {'keyword': '卓识', 'weight': 10},
    {'keyword': '稳博', 'weight': 10},
    {'keyword': '宽德', 'weight': 10},
    {'keyword': '世纪前沿', 'weight': 10},
    {'keyword': '诚奇', 'weight': 10},
    {'keyword': '金锝', 'weight': 10},
    {'keyword': '启林', 'weight': 10},
    {'keyword': '茂源量化', 'weight': 10},
    {'keyword': '金戈量锐', 'weight': 10},
    {'keyword': '黑翼', 'weight': 10},
    {'keyword': '信弘天禾', 'weight': 10},
    {'keyword': '思勰', 'weight': 10},
    {'keyword': '呜石', 'weight': 10},
    {'keyword': '锐天', 'weight': 10},
    {'keyword': '龙旗科技', 'weight': 10},
    {'keyword': '进化论', 'weight': 10},
    {'keyword': '宽产', 'weight': 10},
    {'keyword': '博普', 'weight': 10},
    {'keyword': '赫富', 'weight': 10},
    {'keyword': '涵德', 'weight': 10},
    {'keyword': '国恩', 'weight': 10},
    {'keyword': '艾方', 'weight': 10},
    {'keyword': '星瑞', 'weight': 10},
    {'keyword': '白鹭', 'weight': 10},
    {'keyword': '因诺', 'weight': 10},
    {'keyword': '凯纳', 'weight': 10},
    {'keyword': '念空念觉', 'weight': 10},
    {'keyword': '千象', 'weight': 10},
    {'keyword': '洛书', 'weight': 10},
    {'keyword': '蒙玺', 'weight': 10},
    {'keyword': '千宜', 'weight': 10},
    {'keyword': '平方和', 'weight': 10},
    {'keyword': '申毅', 'weight': 10},
    {'keyword': '心汉页习', 'weight': 10},
    {'keyword': '乾象', 'weight': 10},
    {'keyword': '盛冠达', 'weight': 10},
    {'keyword': '思晔', 'weight': 10},
    {'keyword': '天算量化', 'weight': 10},
    {'keyword': '图灵量化', 'weight': 10},
    {'keyword': '衍盛', 'weight': 10},
    {'keyword': '象限', 'weight': 10},
    {'keyword': '展弘', 'weight': 10},
    {'keyword': '仲阳天王', 'weight': 10},
    {'keyword': '顽岩', 'weight': 10},
    {'keyword': '致诚卓远', 'weight': 10},
]