# # 关键词列表,每个元素是一个字典,包含关键词和对应权重


# Topic = 低空经济 in 头条资讯
low_altitude_economy_toutiaonews_keywords = [
    {'keyword': '低空物流', 'weight': 10},
    {'keyword': '低空经济', 'weight': 10},
    {'keyword': 'eVTOL', 'weight': 10},
    {'keyword': '低空医疗', 'weight': 10},
    {'keyword': '低空出行', 'weight': 10},
    {'keyword': '低空交通', 'weight': 8},
]

# Topic = 低空经济 in 百度资讯
low_altitude_economy_baidunews_keywords = [
    {'keyword': '低空物流', 'weight': 10},
    {'keyword': '低空经济', 'weight': 10},
    {'keyword': 'eVTOL', 'weight': 10},
    {'keyword': '低空医疗', 'weight': 10},
    {'keyword': '低空出行', 'weight': 10},
    {'keyword': '低空交通', 'weight': 8},
]

# Topic = 商业航天 in 头条资讯
commercial_space_toutiaonews_keywords = [
    {'keyword': '商业航天', 'weight': 9.5},
    {'keyword': '星舰', 'weight': 10},
    {'keyword': 'star ship', 'weight': 10},
    {'keyword': '星链', 'weight': 9.5},
    {'keyword': 'star link', 'weight': 10},
    {'keyword': '猎鹰火箭', 'weight': 10},
    {'keyword': '猎鹰9号', 'weight': 10},
    {'keyword': '猎鹰重型', 'weight': 10},
    {'keyword': 'spacex', 'weight': 9.0},
    {'keyword': '卫星互联网', 'weight': 9.0},
    {'keyword': '低轨卫星', 'weight': 9.0},
    {'keyword': '中国卫星通信集团', 'weight': 8},
    {'keyword': '中国卫通', 'weight': 8},
    {'keyword': '上海微小卫星', 'weight': 8},
    {'keyword': '航天长峰', 'weight': 8},
    {'keyword': '长峰航天', 'weight': 8},
    {'keyword': '银河航天', 'weight': 8},
    {'keyword': '银河互联网', 'weight': 8},
    {'keyword': 'Galactic Network', 'weight': 8},
    {'keyword': '蓝箭', 'weight': 10},
    {'keyword': 'LandSpace', 'weight': 8},
    {'keyword': '星际荣耀', 'weight': 10},
    {'keyword': 'iSpace', 'weight': 8},
    {'keyword': '零壹空间', 'weight': 10},
    {'keyword': 'OneSpace', 'weight': 8},
    {'keyword': '中科微星', 'weight': 7},
    {'keyword': '星网', 'weight': 9},
    {'keyword': 'China Satellite Network', 'weight': 9},
    {'keyword': '鸿雁星座', 'weight': 8},
    {'keyword': '虹云', 'weight': 8},
    {'keyword': '快舟', 'weight': 8},
]

# Topic = 商业航天 in 百度资讯
commercial_space_baidunews_keywords = [
    {'keyword': '商业航天', 'weight': 9.5},
    {'keyword': '星舰', 'weight': 10},
    {'keyword': 'star ship', 'weight': 10},
    {'keyword': '星链', 'weight': 9.5},
    {'keyword': 'star link', 'weight': 10},
    {'keyword': '猎鹰火箭', 'weight': 10},
    {'keyword': '猎鹰9号', 'weight': 10},
    {'keyword': '猎鹰重型', 'weight': 10},
    {'keyword': 'spacex', 'weight': 9.0},
    {'keyword': '卫星互联网', 'weight': 9.0},
    {'keyword': '低轨卫星', 'weight': 9.0},
    {'keyword': '中国卫星通信集团', 'weight': 8},
    {'keyword': '中国卫通', 'weight': 8},
    {'keyword': '上海微小卫星', 'weight': 8},
    {'keyword': '航天长峰', 'weight': 8},
    {'keyword': '长峰航天', 'weight': 8},
    {'keyword': '银河航天', 'weight': 8},
    {'keyword': '银河互联网', 'weight': 8},
    {'keyword': 'Galactic Network', 'weight': 8},
    {'keyword': '蓝箭', 'weight': 10},
    {'keyword': 'LandSpace', 'weight': 8},
    {'keyword': '星际荣耀', 'weight': 10},
    {'keyword': 'iSpace', 'weight': 8},
    {'keyword': '零壹空间', 'weight': 10},
    {'keyword': 'OneSpace', 'weight': 8},
    {'keyword': '中科微星', 'weight': 7},
    {'keyword': '星网', 'weight': 9},
    {'keyword': 'China Satellite Network', 'weight': 9},
    {'keyword': '鸿雁星座', 'weight': 8},
    {'keyword': '虹云', 'weight': 8},
    {'keyword': '快舟', 'weight': 8},
]

# Topic = 生物制造 in 头条资讯
Biomanufacturing_toutiaonews_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    {'keyword': '合成生物', 'weight': 10},
    {'keyword': 'bio-made', 'weight': 10},
    {'keyword': '蛋白合成', 'weight': 10},
    {'keyword': '合成蛋白', 'weight': 10},
    {'keyword': '人造肉', 'weight': 10},
]

# Topic = 生物制造 in 百度资讯
Biomanufacturing_baidunews_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    {'keyword': '合成生物', 'weight': 10},
    {'keyword': 'bio-made', 'weight': 10},
    {'keyword': '蛋白合成', 'weight': 10},
    {'keyword': '合成蛋白', 'weight': 10},
    {'keyword': '人造肉', 'weight': 10},
]

# Topic = 先锋热点 in 头条资讯
HotPoint_toutiaonews_keywords = [
    {'keyword': 'p70', 'weight': 10},
    {'keyword': '董宇辉', 'weight': 10},
    {'keyword': '与辉同行', 'weight': 10},
    {'keyword': '人形机器人', 'weight': 10},
    {'keyword': '固态电池', 'weight': 10},
    {'keyword': '马斯克', 'weight': 10},
    {'keyword': 'elon musk', 'weight': 10},
    {'keyword': '小米汽车', 'weight': 10},
    {'keyword': 'su7', 'weight': 10},
    {'keyword': 'su8', 'weight': 10},
    {'keyword': '小米suv', 'weight': 10},
    {'keyword': 'V8S超级电机', 'weight': 8},
    {'keyword': '江波龙', 'weight': 8},
]

# Topic = 先锋热点 in 百度资讯
HotPoint_baidunews_keywords = [
    {'keyword': 'p70', 'weight': 10},
    {'keyword': '董宇辉', 'weight': 10},
    {'keyword': '与辉同行', 'weight': 10},
    {'keyword': '人形机器人', 'weight': 10},
    {'keyword': '固态电池', 'weight': 10},
    {'keyword': '马斯克', 'weight': 10},
    {'keyword': 'elon musk', 'weight': 10},
    {'keyword': '小米汽车', 'weight': 10},
    {'keyword': 'su7', 'weight': 10},
    {'keyword': 'su8', 'weight': 10},
    {'keyword': '小米suv', 'weight': 10},
    {'keyword': 'V8S超级电机', 'weight': 8},
    {'keyword': '江波龙', 'weight': 8},
]

# Topic = AI算力 in 头条资讯
AIHPC_toutiaonews_keywords = [
    # AI概念
    {'keyword': 'AGI', 'weight': 10},
    {'keyword': 'ASI', 'weight': 10},
    # AI公司产品人物
    {'keyword': 'openai', 'weight': 10},
    {'keyword': 'gpt5', 'weight': 10},
    {'keyword': 'gpt 5', 'weight': 10},
    {'keyword': 'gpt-5', 'weight': 10},
    {'keyword': 'gpt4.5', 'weight': 10},
    {'keyword': 'gpt 4.5', 'weight': 10},
    {'keyword': 'gpt-4.5', 'weight': 10},
    {'keyword': 'Ilya', 'weight': 10},
    {'keyword': 'Sam Altman', 'weight': 10},
    {'keyword': '山姆·奥特曼', 'weight': 10},
    {'keyword': 'kimi', 'weight': 10},
    {'keyword': 'chatglm', 'weight': 10},
    {'keyword': 'sora', 'weight': 10},
    # 算力芯片
    {'keyword': '算力芯片', 'weight': 10},
    {'keyword': 'AI芯片', 'weight': 10},
    {'keyword': 'nv', 'weight': 10},
    {'keyword': 'nvida', 'weight': 10},
    {'keyword': '黄仁勋', 'weight': 10},
    {'keyword': 'A100', 'weight': 10},
    {'keyword': 'B200', 'weight': 10},
    {'keyword': 'tpu', 'weight': 10},
    # 算通一体化
    {'keyword': 'nv link', 'weight': 10},
    {'keyword': '硅光', 'weight': 10},
    {'keyword': 'silicon photonic', 'weight': 10},
    {'keyword': '光互联', 'weight': 10},
    {'keyword': 'optical interconnects', 'weight': 10},
    {'keyword': 'optical interconnect', 'weight': 10},
    {'keyword': 'CPO', 'weight': 10},
    {'keyword': 'OCS', 'weight': 10},
    {'keyword': 'CXL', 'weight': 10},
    {'keyword': 'compute express link', 'weight': 10},
    {'keyword': 'ayar', 'weight': 10},
]

# Topic = AI算力 in 百度资讯
AIHPC_baidunews_keywords = [
    # AI概念
    {'keyword': 'AGI', 'weight': 10},
    {'keyword': 'ASI', 'weight': 10},
    # AI公司产品人物
    {'keyword': 'openai', 'weight': 10},
    {'keyword': 'gpt5', 'weight': 10},
    {'keyword': 'gpt 5', 'weight': 10},
    {'keyword': 'gpt-5', 'weight': 10},
    {'keyword': 'gpt4.5', 'weight': 10},
    {'keyword': 'gpt 4.5', 'weight': 10},
    {'keyword': 'gpt-4.5', 'weight': 10},
    {'keyword': 'Ilya', 'weight': 10},
    {'keyword': 'Sam Altman', 'weight': 10},
    {'keyword': '山姆·奥特曼', 'weight': 10},
    {'keyword': 'kimi', 'weight': 10},
    {'keyword': 'chatglm', 'weight': 10},
    {'keyword': 'sora', 'weight': 10},
    # 算力芯片
    {'keyword': '算力芯片', 'weight': 10},
    {'keyword': 'AI芯片', 'weight': 10},
    {'keyword': 'nv', 'weight': 10},
    {'keyword': 'nvida', 'weight': 10},
    {'keyword': '黄仁勋', 'weight': 10},
    {'keyword': 'A100', 'weight': 10},
    {'keyword': 'B200', 'weight': 10},
    {'keyword': 'tpu', 'weight': 10},
    # 算通一体化
    {'keyword': 'nv link', 'weight': 10},
    {'keyword': '硅光', 'weight': 10},
    {'keyword': 'silicon photonic', 'weight': 10},
    {'keyword': '光互联', 'weight': 10},
    {'keyword': 'optical interconnects', 'weight': 10},
    {'keyword': 'optical interconnect', 'weight': 10},
    {'keyword': 'CPO', 'weight': 10},
    {'keyword': 'OCS', 'weight': 10},
    {'keyword': 'CXL', 'weight': 10},
    {'keyword': 'compute express link', 'weight': 10},
    {'keyword': 'ayar', 'weight': 10},
]

# Topic = Lidar智驾 in 头条资讯
LidarADAS_toutiaonews_keywords = [
    {'keyword': '激光雷达', 'weight': 10},
    {'keyword': '激光雷达 低空经济', 'weight': 10},
    {'keyword': '激光雷达 低空无人', 'weight': 10},
    {'keyword': '激光雷达 低空交通', 'weight': 10},
    {'keyword': '激光雷达 低空物流', 'weight': 10},
    {'keyword': '激光雷达 无人物流', 'weight': 10},
    {'keyword': '激光雷达 智能网联', 'weight': 10},
    {'keyword': '激光雷达 v2x', 'weight': 10},
    {'keyword': 'Lidar', 'weight': 10},
    {'keyword': 'FMCW', 'weight': 10},
    {'keyword': 'OPA', 'weight': 10},
    {'keyword': '智驾', 'weight': 10},
    {'keyword': '禾赛', 'weight': 10},
    {'keyword': '速腾聚创', 'weight': 10},
    {'keyword': '图达通', 'weight': 10},
    {'keyword': '华为激光雷达', 'weight': 10},
    {'keyword': '镭神', 'weight': 10},
    {'keyword': '一径科技', 'weight': 10},
    {'keyword': '大疆览沃', 'weight': 10},
    {'keyword': '北醒', 'weight': 10},
    {'keyword': '探维', 'weight': 10},
    {'keyword': '洛微', 'weight': 10},
    {'keyword': '摩尔芯光', 'weight': 10},
    {'keyword': '万集科技', 'weight': 10},
    {'keyword': '炬光科技', 'weight': 10},
    {'keyword': '长光华芯', 'weight': 10},
    {'keyword': '芯视界', 'weight': 10},
    {'keyword': '阜时', 'weight': 10},
    {'keyword': '识光', 'weight': 10},
    {'keyword': '纵慧芯光', 'weight': 10},
    {'keyword': '奥比中光', 'weight': 10},
    {'keyword': '永新光学', 'weight': 10},
    {'keyword': '蓝特光学', 'weight': 10},
    {'keyword': 'Luminar', 'weight': 10},
    {'keyword': 'Aeva', 'weight': 10},
    {'keyword': 'Ouster', 'weight': 10},
    {'keyword': '奥锐达', 'weight': 10},
    {'keyword': '天眸光电', 'weight': 10},
    {'keyword': '北科天绘', 'weight': 10},
    {'keyword': '激光雷达研报', 'weight': 10},
    {'keyword': '激光雷达深度报告', 'weight': 10},
    {'keyword': '激光雷达研究报告', 'weight': 10},
    {'keyword': '激光雷达行业报告', 'weight': 10},
    {'keyword': '毫米波雷达研报', 'weight': 10},
    {'keyword': '毫米波雷达深度报告', 'weight': 10},
    {'keyword': '毫米波雷达研究报告', 'weight': 10},
    {'keyword': '毫米波雷达行业报告', 'weight': 10},
    {'keyword': '智能网联', 'weight': 10},
    {'keyword': '车路协同', 'weight': 10},
    {'keyword': 'V2X', 'weight': 10},
    {'keyword': '无人配送', 'weight': 10},
    {'keyword': '无人物流', 'weight': 10},
    {'keyword': 'Robobus', 'weight': 10},
    {'keyword': 'Robotaxi', 'weight': 10},
    {'keyword': '无人货车', 'weight': 10},
    {'keyword': 'Robotruck', 'weight': 10},
    {'keyword': '新石器无人车', 'weight': 10},
    {'keyword': '美团无人车', 'weight': 10},
    {'keyword': '阿里小蛮驴无人车', 'weight': 10},
    {'keyword': '京东无人车', 'weight': 10},
    {'keyword': '百度Robotaxi', 'weight': 10},
    {'keyword': '萝卜快跑', 'weight': 10},
    {'keyword': '滴滴自动驾驶', 'weight': 10},
    {'keyword': '智加科技', 'weight': 10},
    {'keyword': '禾多科技', 'weight': 10},
    {'keyword': 'Momenta', 'weight': 10},
    {'keyword': '文远知行', 'weight': 10},
    {'keyword': '小马智行', 'weight': 10},
    {'keyword': '元戎启行', 'weight': 10},
]



# Topic = Lidar智驾 in 百度资讯
LidarADAS_baidunews_keywords = [
    {'keyword': '激光雷达', 'weight': 10},
    {'keyword': '激光雷达 低空经济', 'weight': 10},
    {'keyword': '激光雷达 低空无人', 'weight': 10},
    {'keyword': '激光雷达 低空物流', 'weight': 10},
    {'keyword': '激光雷达 低空交通', 'weight': 10},
    {'keyword': '激光雷达 无人物流', 'weight': 10},
    {'keyword': '激光雷达 智能网联', 'weight': 10},
    {'keyword': '激光雷达 v2x', 'weight': 10},
    {'keyword': 'Lidar', 'weight': 10},
    {'keyword': 'FMCW', 'weight': 10},
    {'keyword': 'OPA', 'weight': 10},
    {'keyword': '智驾', 'weight': 10},
    {'keyword': '禾赛', 'weight': 10},
    {'keyword': '速腾聚创', 'weight': 10},
    {'keyword': '图达通', 'weight': 10},
    {'keyword': '华为激光雷达', 'weight': 10},
    {'keyword': '镭神', 'weight': 10},
    {'keyword': '一径科技', 'weight': 10},
    {'keyword': '大疆览沃', 'weight': 10},
    {'keyword': '北醒', 'weight': 10},
    {'keyword': '探维', 'weight': 10},
    {'keyword': '洛微', 'weight': 10},
    {'keyword': '摩尔芯光', 'weight': 10},
    {'keyword': '万集科技', 'weight': 10},
    {'keyword': '炬光科技', 'weight': 10},
    {'keyword': '长光华芯', 'weight': 10},
    {'keyword': '芯视界', 'weight': 10},
    {'keyword': '阜时', 'weight': 10},
    {'keyword': '识光', 'weight': 10},
    {'keyword': '纵慧芯光', 'weight': 10},
    {'keyword': '奥比中光', 'weight': 10},
    {'keyword': '永新光学', 'weight': 10},
    {'keyword': '蓝特光学', 'weight': 10},
    {'keyword': 'Luminar', 'weight': 10},
    {'keyword': 'Aeva', 'weight': 10},
    {'keyword': 'Ouster', 'weight': 10},
    {'keyword': '奥锐达', 'weight': 10},
    {'keyword': '天眸光电', 'weight': 10},
    {'keyword': '北科天绘', 'weight': 10},
    {'keyword': '激光雷达研报', 'weight': 10},
    {'keyword': '激光雷达深度报告', 'weight': 10},
    {'keyword': '激光雷达研究报告', 'weight': 10},
    {'keyword': '激光雷达行业报告', 'weight': 10},
    {'keyword': '毫米波雷达研报', 'weight': 10},
    {'keyword': '毫米波雷达深度报告', 'weight': 10},
    {'keyword': '毫米波雷达研究报告', 'weight': 10},
    {'keyword': '毫米波雷达行业报告', 'weight': 10},
    {'keyword': '智能网联', 'weight': 10},
    {'keyword': '车路协同', 'weight': 10},
    {'keyword': 'V2X', 'weight': 10},
    {'keyword': '无人配送', 'weight': 10},
    {'keyword': '无人物流', 'weight': 10},
    {'keyword': 'Robobus', 'weight': 10},
    {'keyword': 'Robotaxi', 'weight': 10},
    {'keyword': '无人货车', 'weight': 10},
    {'keyword': 'Robotruck', 'weight': 10},
    {'keyword': '新石器无人车', 'weight': 10},
    {'keyword': '美团无人车', 'weight': 10},
    {'keyword': '阿里小蛮驴无人车', 'weight': 10},
    {'keyword': '京东无人车', 'weight': 10},
    {'keyword': '百度Robotaxi', 'weight': 10},
    {'keyword': '萝卜快跑', 'weight': 10},
    {'keyword': '滴滴自动驾驶', 'weight': 10},
    {'keyword': '智加科技', 'weight': 10},
    {'keyword': '禾多科技', 'weight': 10},
    {'keyword': 'Momenta', 'weight': 10},
    {'keyword': '文远知行', 'weight': 10},
    {'keyword': '小马智行', 'weight': 10},
    {'keyword': '元戎启行', 'weight': 10},
]

# Topic = 量化 in 头条资讯
quantitative_trading_toutiaonews_keywords = [
    # {'keyword': '量化', 'weight': 10},
    {'keyword': '对冲', 'weight': 10},
    {'keyword': '对冲基金', 'weight': 10},
    {'keyword': '量化私募', 'weight': 10},
    {'keyword': '量化基金', 'weight': 10},
    {'keyword': '量化交易', 'weight': 10},
    {'keyword': 'dma量化交易', 'weight': 10},
    {'keyword': '高频交易', 'weight': 10},
    {'keyword': 'smart beta', 'weight': 10},
    {'keyword': 'smart贝塔', 'weight': 10},
    {'keyword': 'smart β', 'weight': 10},
    {'keyword': 'etf套利', 'weight': 10},
    {'keyword': '宽基对冲', 'weight': 10},
    {'keyword': '跨品种套利', 'weight': 8},
    {'keyword': '量化选股', 'weight': 8},
    {'keyword': '量化择时', 'weight': 8},
    {'keyword': '指数增强', 'weight': 6},
    {'keyword': '均值回复', 'weight': 7},
    {'keyword': '幻方量化', 'weight': 10},
    {'keyword': '明汯量化', 'weight': 10},
    {'keyword': '灵均量化', 'weight': 10},
    {'keyword': '九坤量化', 'weight': 10},
    {'keyword': '衍复量化', 'weight': 10},
    {'keyword': '天演量化', 'weight': 10},
    {'keyword': '卓识量化', 'weight': 10},
    {'keyword': '稳博量化', 'weight': 10},
    {'keyword': '宽德量化', 'weight': 10},
    {'keyword': '诚奇量化', 'weight': 10},
    {'keyword': '金锝量化', 'weight': 10},
    {'keyword': '启林量化', 'weight': 10},
    {'keyword': '茂源量化', 'weight': 10},
    {'keyword': '金戈量锐', 'weight': 10},
    {'keyword': '黑翼量化', 'weight': 10},
    {'keyword': '信弘天禾', 'weight': 10},
    {'keyword': '思勰量化', 'weight': 10},
    {'keyword': '呜石量化', 'weight': 10},
    {'keyword': '锐天量化', 'weight': 10},
    {'keyword': '龙旗科技', 'weight': 10},
    {'keyword': '进化论量化', 'weight': 10},
    {'keyword': '宽产量化', 'weight': 10},
    {'keyword': '博普量化', 'weight': 10},
    {'keyword': '赫富量化', 'weight': 10},
    {'keyword': '涵德量化', 'weight': 10},
    {'keyword': '国恩量化', 'weight': 10},
    {'keyword': '艾方量化', 'weight': 10},
    {'keyword': '星瑞量化', 'weight': 10},
    {'keyword': '白鹭量化', 'weight': 10},
    {'keyword': '因诺量化', 'weight': 10},
    {'keyword': '凯纳量化', 'weight': 10},
    {'keyword': '念空念觉量化', 'weight': 10},
    {'keyword': '千象量化', 'weight': 10},
    {'keyword': '洛书量化', 'weight': 10},
    {'keyword': '蒙玺量化', 'weight': 10},
    {'keyword': '千宜量化', 'weight': 10},
    {'keyword': '平方和量化', 'weight': 10},
    {'keyword': '申毅量化', 'weight': 10},
    {'keyword': '心汉页习', 'weight': 10},
    {'keyword': '乾象量化', 'weight': 10},
    {'keyword': '盛冠达量化', 'weight': 10},
    {'keyword': '思晔量化', 'weight': 10},
    {'keyword': '天算量化', 'weight': 10},
    {'keyword': '图灵量化', 'weight': 10},
    {'keyword': '衍盛量化', 'weight': 10},
    {'keyword': '象限量化', 'weight': 10},
    {'keyword': '展弘量化', 'weight': 10},
    {'keyword': '仲阳天王量化', 'weight': 10},
    {'keyword': '顽岩量化', 'weight': 10},
    {'keyword': '致诚卓远', 'weight': 10},
]

# Topic = 量化 in 百度资讯
quantitative_trading_baidunews_keywords = [
    # {'keyword': '量化', 'weight': 10},
    {'keyword': '对冲', 'weight': 10},
    {'keyword': '对冲基金', 'weight': 10},
    {'keyword': '量化私募', 'weight': 10},
    {'keyword': '量化基金', 'weight': 10},
    {'keyword': '量化交易', 'weight': 10},
    {'keyword': 'dma量化交易', 'weight': 10},
    {'keyword': '高频交易', 'weight': 10},
    {'keyword': 'smart beta', 'weight': 10},
    {'keyword': 'smart贝塔', 'weight': 10},
    {'keyword': 'smart β', 'weight': 10},
    {'keyword': 'etf套利', 'weight': 10},
    {'keyword': '宽基对冲', 'weight': 10},
    {'keyword': '跨品种套利', 'weight': 8},
    {'keyword': '量化选股', 'weight': 8},
    {'keyword': '量化择时', 'weight': 8},
    {'keyword': '指数增强', 'weight': 6},
    {'keyword': '均值回复', 'weight': 7},
    {'keyword': '幻方量化', 'weight': 10},
    {'keyword': '明汯量化', 'weight': 10},
    {'keyword': '灵均量化', 'weight': 10},
    {'keyword': '九坤量化', 'weight': 10},
    {'keyword': '衍复量化', 'weight': 10},
    {'keyword': '天演量化', 'weight': 10},
    {'keyword': '卓识量化', 'weight': 10},
    {'keyword': '稳博量化', 'weight': 10},
    {'keyword': '宽德量化', 'weight': 10},
    {'keyword': '诚奇量化', 'weight': 10},
    {'keyword': '金锝量化', 'weight': 10},
    {'keyword': '启林量化', 'weight': 10},
    {'keyword': '茂源量化', 'weight': 10},
    {'keyword': '金戈量锐', 'weight': 10},
    {'keyword': '黑翼量化', 'weight': 10},
    {'keyword': '信弘天禾', 'weight': 10},
    {'keyword': '思勰量化', 'weight': 10},
    {'keyword': '呜石量化', 'weight': 10},
    {'keyword': '锐天量化', 'weight': 10},
    {'keyword': '龙旗科技', 'weight': 10},
    {'keyword': '进化论量化', 'weight': 10},
    {'keyword': '宽产量化', 'weight': 10},
    {'keyword': '博普量化', 'weight': 10},
    {'keyword': '赫富量化', 'weight': 10},
    {'keyword': '涵德量化', 'weight': 10},
    {'keyword': '国恩量化', 'weight': 10},
    {'keyword': '艾方量化', 'weight': 10},
    {'keyword': '星瑞量化', 'weight': 10},
    {'keyword': '白鹭量化', 'weight': 10},
    {'keyword': '因诺量化', 'weight': 10},
    {'keyword': '凯纳量化', 'weight': 10},
    {'keyword': '念空念觉量化', 'weight': 10},
    {'keyword': '千象量化', 'weight': 10},
    {'keyword': '洛书量化', 'weight': 10},
    {'keyword': '蒙玺量化', 'weight': 10},
    {'keyword': '千宜量化', 'weight': 10},
    {'keyword': '平方和量化', 'weight': 10},
    {'keyword': '申毅量化', 'weight': 10},
    {'keyword': '心汉页习', 'weight': 10},
    {'keyword': '乾象量化', 'weight': 10},
    {'keyword': '盛冠达量化', 'weight': 10},
    {'keyword': '思晔量化', 'weight': 10},
    {'keyword': '天算量化', 'weight': 10},
    {'keyword': '图灵量化', 'weight': 10},
    {'keyword': '衍盛量化', 'weight': 10},
    {'keyword': '象限量化', 'weight': 10},
    {'keyword': '展弘量化', 'weight': 10},
    {'keyword': '仲阳天王量化', 'weight': 10},
    {'keyword': '顽岩量化', 'weight': 10},
    {'keyword': '致诚卓远', 'weight': 10},
]