# # 关键词列表,每个元素是一个字典,包含关键词和对应权重

# Topic = 大AI in 头条资讯
ai_toutiaonews_keywords = [
    # 自动驾驶
    {'keyword': 'V2X', 'weight': 10},
    {"keyword": "千里浩瀚", "weight": 6},
    {'keyword': 'Robobus', 'weight': 10},
    {'keyword': 'Robotaxi', 'weight': 10},
	{'keyword': 'Robotruck', 'weight': 10},
    {'keyword': 'Robovan', 'weight': 10},
    # {'keyword': '无人货车', 'weight': 10},
    # {"keyword": "无人农机", "weight": 7},
    {"keyword": "无人配送", "weight": 8},
    {"keyword": "无人物流", "weight": 8},
    # {"keyword": "物流机器人", "weight": 8},
    # {"keyword": "环卫机器人", "weight": 8},
    # {"keyword": "消毒机器人", "weight": 7},
    {"keyword": "小蛮驴", "weight": 8},
    {"keyword": "新石器", "weight": 7},
    # {"keyword": "巡逻机器人", "weight": 7},
    # {"keyword": "医疗机器人", "weight": 9},
    # {"keyword": "宇通环卫", "weight": 7},
    # {"keyword": "云创智行", "weight": 6},
    # {"keyword": "智慧环卫", "weight": 7},
    {"keyword": "九识", "weight": 7},
    {"keyword": "澜舟", "weight": 7},
    # {"keyword": "幂律智能", "weight": 7},
    # {"keyword": "面壁智能", "weight": 7},
    # {"keyword": "瑞莱智慧", "weight": 7},
    {"keyword": "深势科技", "weight": 7},
    {"keyword": "Aurora", "weight": 8},
    {"keyword": "AutoX", "weight": 8},
    {"keyword": "Mobileye", "weight": 9},
    {"keyword": "Momenta", "weight": 8},
    {"keyword": "Nuro", "weight": 8},
    {"keyword": "Waymo", "weight": 10},
    {"keyword": "Wayve", "weight": 8},
    {"keyword": "白犀牛", "weight": 7},
    {"keyword": "百度Apollo", "weight": 9},
    {"keyword": "滴滴自动驾驶", "weight": 8},
    {'keyword': '美团无人车', 'weight': 10},
    {'keyword': '京东无人车', 'weight': 10},
    {'keyword': '百度Robotaxi', 'weight': 10},
    # {"keyword": "伯镭科技", "weight": 7},
    # {"keyword": "飞步科技", "weight": 7},
    # {"keyword": "畅行智能", "weight": 7},
    # {"keyword": "海鹏智车", "weight": 7},
    {"keyword": "毫末智行", "weight": 8},
    # {"keyword": "宏景智驾", "weight": 7},
    # {"keyword": "慧拓智能", "weight": 7},
    # {"keyword": "济驭科技", "weight": 6},
    {"keyword": "酷哇科技", "weight": 7},
    # {"keyword": "路凯智行", "weight": 6},
    {"keyword": "萝卜快跑", "weight": 8},
    # {"keyword": "盟识科技", "weight": 7},
    {"keyword": "轻舟智航", "weight": 7},
    {"keyword": "商汤绝影", "weight": 8},
    # {"keyword": "胜途智能", "weight": 6},
    {"keyword": "斯年智驾", "weight": 6},
    {"keyword": "踏歌智行", "weight": 6},
    {"keyword": "同创智驾", "weight": 6},
    {"keyword": "图森未来", "weight": 8},
    {"keyword": "文远知行", "weight": 8},
    {"keyword": "希迪智驾", "weight": 7},
    {"keyword": "仙途智能", "weight": 7},
    {"keyword": "小马智行", "weight": 9},
    {'keyword': '禾多科技', 'weight': 10},
    {"keyword": "一清创新", "weight": 6},
    {"keyword": "易控智驾", "weight": 6},
    {"keyword": "赢彻科技", "weight": 8},
    {"keyword": "友道智途", "weight": 7},
    {"keyword": "驭势科技", "weight": 8},
    {"keyword": "元戎启行", "weight": 8},
    {"keyword": "智加科技", "weight": 7},
    {"keyword": "智行者", "weight": 7},
    {"keyword": "中科慧拓", "weight": 7},
    {"keyword": "主线科技", "weight": 7},
    {"keyword": "卓驭", "weight": 6},
    {"keyword": "纵目科技", "weight": 7},

    # 机器人概念
    # {"keyword": "机器人小脑", "weight": 8},
    # {"keyword": "机器人大脑", "weight": 8},
    # {"keyword": "机器人操作系统", "weight": 8},
    # {"keyword": "机器人传感器", "weight": 8},
    # {"keyword": "机器人感知", "weight": 8},
    # {"keyword": "机器人运动控制", "weight": 8},
    # {"keyword": "机器人执行器", "weight": 7},
    # {"keyword": "机器视觉", "weight": 9},

    # 0自由度、陪伴器人
    {"keyword": "陪伴机器人", "weight": 6},

    # 低自由度、工具机器人
    # {"keyword": "亿嘉和", "weight": 9},
    # {"keyword": "洛必德", "weight": 9},
    # {"keyword": "霞智", "weight": 9},
    # {"keyword": "高仙", "weight": 9},
    # {"keyword": "有鹿同行", "weight": 9},
    # {"keyword": "智行者", "weight": 9},
    # {"keyword": "齐元智能", "weight": 9},
    # {"keyword": "欣佰特", "weight": 9},
    {"keyword": "追觅", "weight": 7},
    # {"keyword": "安防机器人", "weight": 7},
    # {"keyword": "搬运机器人", "weight": 7},
    # {"keyword": "餐饮机器人", "weight": 7},
    # {"keyword": "仓储机器人", "weight": 8},
    # {"keyword": "分拣机器人", "weight": 8},
    # {"keyword": "服务机器人", "weight": 8},
    # {"keyword": "极飞科技", "weight": 7},
    # {"keyword": "家居机器人", "weight": 7},
    # {"keyword": "建筑机器人", "weight": 6},
    # {"keyword": "教育机器人", "weight": 7},
    # {"keyword": "救援机器人", "weight": 8},
    # {"keyword": "康复机器人", "weight": 7},
    # {"keyword": "零售机器人", "weight": 7},
    # {"keyword": "农业机器人", "weight": 7},
    # {"keyword": "陪伴机器人", "weight": 7},
    # {"keyword": "普渡机器人", "weight": 7},
    # {"keyword": "清扫机器人", "weight": 7},
    {"keyword": "赛特智能", "weight": 7},

    #高自由度、人形机器人、机器狗
    # {"keyword": "人形机器人", "weight": 9},
    {"keyword": "软银机器人", "weight": 8},
    {"keyword": "赛力斯机器人", "weight": 6},
    {"keyword": "深蓝科技", "weight": 6},
    # {"keyword": "四川具身", "weight": 6},
    {"keyword": "腾讯机器人", "weight": 8},
    {"keyword": "字节跳动机器人", "weight": 8},
    # {"keyword": "腾讯小五", "weight": 6},
    {"keyword": "天准星智", "weight": 6},
    {"keyword": "西井科技", "weight": 7},
    {"keyword": "小米机器人", "weight": 8},
    {"keyword": "小鹏机器人", "weight": 7},
    # {"keyword": "逐步智能", "weight": 6},
    {"keyword": "行深智能", "weight": 7},
    # {"keyword": "尧舜禹", "weight": 6},
    {"keyword": "银河通用", "weight": 6},
    {"keyword": "优必选", "weight": 8},
    # {"keyword": "优必选Alpha", "weight": 7},
    # {"keyword": "优必选Walker", "weight": 8},
    {"keyword": "宇树", "weight": 7},
    # {"keyword": "宇树B1", "weight": 6},
    # {"keyword": "宇树B2", "weight": 6},
    # {"keyword": "宇树Go1", "weight": 7},
    # {"keyword": "跃薪智能", "weight": 6},
    {"keyword": "长安汽车机器人", "weight": 7},
    # {"keyword": "中能聪聪", "weight": 6},
    {"keyword": "众擎", "weight": 6},
    {"keyword": "星海图", "weight": 8},
    {"keyword": "自变量", "weight": 8},
    {"keyword": "千寻", "weight": 8},
    {"keyword": "阿里机器人", "weight": 8},
    # {"keyword": "艾欧智能", "weight": 6},
    {"keyword": "北京人形机器人创新中心", "weight": 8},
    {"keyword": "比亚迪机器人", "weight": 7},
    {"keyword": "吉利汽车机器人", "weight": 7},
    {"keyword": "波士顿动力", "weight": 10},
    # {"keyword": "蚕丛机器人", "weight": 6},
    {"keyword": "高仙机器人", "weight": 7},
    {"keyword": "高仙智能", "weight": 7},
    {"keyword": "广汽机器人", "weight": 7},
    # {"keyword": "海神机器人", "weight": 6},
    {"keyword": "华为机器人", "weight": 9},
    # {"keyword": "机器人操作系统", "weight": 8},
    {"keyword": "灵巧手", "weight": 8},
    {"keyword": "加速进化", "weight": 7},
    {"keyword": "开普勒机器人", "weight": 6},
    {"keyword": "傅里叶机器人", "weight": 6},
    {"keyword": "库萨科技", "weight": 6},
    {"keyword": "乐聚机器人", "weight": 7},
    {"keyword": "Figure AI", "weight": 7},
    {"keyword": "智元", "weight": 6},
    {"keyword": "逐际", "weight": 6},
    {"keyword": "云深处", "weight": 6},
    # {"keyword": "Agility Robotics", "weight": 8},
    # {"keyword": "理想汽车机器人", "weight": 7},
    # {"keyword": "灵汐科技", "weight": 7},
    {"keyword": "魔法原子", "weight": 6},
    {"keyword": "松延动力", "weight": 6},
    # {"keyword": "蓝点触控", "weight": 9},
    {"keyword": "绿地谐波", "weight": 9},
    {"keyword": "Figure机器人", "weight": 9},
    # {"keyword": "陶世减速机", "weight": 9},
    # {"keyword": "陶世机器人", "weight": 9},
    # {"keyword": "金钢编码器", "weight": 9},
    # {"keyword": "巨蟹智能机器人", "weight": 9},
    # {"keyword": "鑫精诚", "weight": 9},
    # {"keyword": "脉塔智能", "weight": 9},
    {"keyword": "他山传感器", "weight": 9},
    {"keyword": "灵心巧手", "weight": 9},
    {"keyword": "PNP Franka", "weight": 9},
    # {"keyword": "华威科", "weight": 9},
    {"keyword": "高擎机器人", "weight": 9},
    {"keyword": "外骨骼", "weight": 7},
    {"keyword": "电子皮肤", "weight": 7},
    {"keyword": "星动纪元", "weight": 6},
    {"keyword": "地瓜机器人", "weight": 8},



    # {"keyword": "ViLLA", "weight": 7},
    # {"keyword": "3D-VLA", "weight": 7},
    # {"keyword": "Atlas", "weight": 9},
    {"keyword": "Cyber One", "weight": 7},
    {"keyword": "Figure 01", "weight": 6},
    {"keyword": "Figure 02", "weight": 6},
    {"keyword": "BotQ", "weight": 7},
    {"keyword": "Helix", "weight": 6},
    {"keyword": "小鹏Iron", "weight": 6},
    # {"keyword": "MindVLA", "weight": 7},
    {"keyword": "NVIDIA Cosmos", "weight": 7},
    # {"keyword": "OpenVLA", 'weight': 7},
    {"keyword": "Physical Intelligence", "weight": 7},
    # {"keyword": "Roboflamingo", "weight": 7},
    # {"keyword": "SA01", "weight": 6},
    # {"keyword": "SE01", "weight": 6},
    # {"keyword": "Spot", "weight": 9},
    # {"keyword": "VLA Spirit", "weight": 7},
    # {"keyword": "Well-Bot", "weight": 6},


    # {"keyword": "亿铸科技", "weight": 6},
    # {"keyword": "智驾芯片", "weight": 8},
    # {"keyword": "中科驭数", "weight": 7},


    # # AI大模型概念
    # {'keyword': 'AGI', 'weight': 10},
    # {'keyword': 'ASI', 'weight': 10},
    # {'keyword': 'AI Agent', 'weight': 10},
    {'keyword': 'Physic AI', 'weight': 10},
    {'keyword': '物理AI', 'weight': 10},
    # {'keyword': 'Deep Research', 'weight': 10},
    # {"keyword": "MoE", "weight": 7},
    # {"keyword": "混合专家系统", "weight": 7},
    # {"keyword": "VLM", "weight": 7},
    # {"keyword": "世界模型", "weight": 7},
    {"keyword": "VLA", "weight": 7},
    # {"keyword": "端到端", "weight": 8},

    # AI人物
    # {'keyword': 'Ilya', 'weight': 10},
    # {'keyword': 'Sam Altman', 'weight': 10},
    # {'keyword': '山姆·奥特曼', 'weight': 10},
    {"keyword": "稚晖君", "weight": 9},
    {"keyword": "王兴兴", "weight": 9},
    {"keyword": "杨立昆", "weight": 9},

    # AI公司产品
    {'keyword': 'openai', 'weight': 10},
    {'keyword': 'gpt5', 'weight': 10},
    {'keyword': 'gpt 5', 'weight': 10},
    {'keyword': 'gpt-5', 'weight': 10},
    {"keyword": "Anthropic", "weight": 8},
    {'keyword': 'gemini', 'weight': 10},
    # {"keyword": "Cohere", "weight": 7},
    {"keyword": "DeepMind", "weight": 10},
    # {"keyword": "H2O.ai", "weight": 7},
    # {"keyword": "Stability AI", "weight": 8},
    # {'keyword': 'Genspark', 'weight': 10},
    {'keyword': 'deepseek', 'weight': 10},
    {'keyword': 'deepseek-r2', 'weight': 10},
    # {'keyword': 'qwen3', 'weight': 10},
    # {'keyword': 'mimo', 'weight': 10},
    # {'keyword': 'healthbench', 'weight': 10},
    # {'keyword': 'keling', 'weight': 10},
    {'keyword': '可灵', 'weight': 10},
    {'keyword': '天工', 'weight': 10},
    {"keyword": "聆心智能", "weight": 6},
    # {"keyword": "Hugging Face", "weight": 9},
    {"keyword": "MiniMax", "weight": 7},
    {"keyword": "海螺AI", "weight": 6},
    {"keyword": "元语智能", "weight": 6},
    {"keyword": "月之暗面", "weight": 6},
    {"keyword": "智谱", "weight": 7},

]

# Topic = 算力 in toutiao
HPC_toutiaonews_keywords= [
    # 算力芯片
    # {'keyword': '算力芯片', 'weight': 10},
    {'keyword': '超节点', 'weight': 10},
    # {'keyword': 'AI芯片', 'weight': 10},
    # {'keyword': 'nv', 'weight': 10},
    {'keyword': 'nvida', 'weight': 10},
    {'keyword': '黄仁勋', 'weight': 10},
    # {'keyword': 'A100', 'weight': 10},
    {'keyword': 'B200', 'weight': 10},
    # {'keyword': 'tpu', 'weight': 10},
    {'keyword': '昇腾', 'weight': 10},
    # {'keyword': '昇腾384', 'weight': 10},
    {'keyword': 'CloudMatrix', 'weight': 10},
    # {'keyword': 'CloudMatrix 384', 'weight': 10},
    # {"keyword": "希姆计算", "weight": 6},
    # {"keyword": "象帝先", "weight": 6},
    # {"keyword": "1X Technologies", "weight": 6},
    # {"keyword": "AI推理芯片", "weight": 8},
    # {"keyword": "AI训练芯片", "weight": 8},
    # {"keyword": "PX5", "weight": 7},
    # {"keyword": "大禹智芯", "weight": 7},
    {"keyword": "地平线", "weight": 9},
    {"keyword": "黑芝麻", "weight": 9},
    {"keyword": "寒武纪", "weight": 9},
    {"keyword": "后摩", "weight": 7},
    # {"keyword": "晶晨", "weight": 7},
    {"keyword": "澜起", "weight": 7},
    {"keyword": "砺算", "weight": 7},
    # {"keyword": "零一万物", "weight": 7},
    {"keyword": "龙芯", "weight": 8},
    {"keyword": "摩尔线程", "weight": 7},
    {"keyword": "沐曦", "weight": 7},
    {"keyword": "平头哥", "weight": 8},
    {"keyword": "瑞芯微", "weight": 7},
    {"keyword": "深鉴", "weight": 7},
    {"keyword": "曙光信息", "weight": 7},
    {"keyword": "燧原", "weight": 7},
    {"keyword": "天数智芯", "weight": 7},
    {"keyword": "芯驰", "weight": 7},
    {"keyword": "芯启源", "weight": 6},
    {"keyword": "芯原微电子", "weight": 7},

    # 算通一体化
    # {'keyword': 'NVLink', 'weight': 10},
    {'keyword': '硅光', 'weight': 10},
    {'keyword': 'silicon photonic', 'weight': 10},
    {'keyword': '光互联', 'weight': 10},
    {'keyword': 'ocs', 'weight': 10},
    {'keyword': 'CPO', 'weight': 10},

    # 量子计算
    # {"keyword": "本源量子", "weight": 7},
    # {"keyword": "光子计算", "weight": 6},
    {"keyword": "量子计算", "weight": 9},
    {"keyword": "曦智", "weight": 9},

    # 先进半导体
    {"keyword": "中芯", "weight": 7},
    {"keyword": "长鑫", "weight": 6},
    {"keyword": "长江存储", "weight": 9},
    {"keyword": "长存", "weight": 9},
    {"keyword": "华虹", "weight": 9},
    {"keyword": "凯美特气", "weight": 9},
    {"keyword": "新凯来", "weight": 9},
    {"keyword": "光刻机", "weight": 9},
    {"keyword": "gkj", "weight": 9},
    {"keyword": "7nm", "weight": 9},
    {"keyword": "5nm", "weight": 9},
    {"keyword": "3nm", "weight": 9},

]

# Topic = ai机器人 in 头条资讯
ai_robot_toutiaonews_keywords = [
]

# Topic = ai机器人 in 百度资讯
ai_robot_baidunews_keywords = [
]


# Topic = 低空经济 in 头条资讯
low_altitude_economy_toutiaonews_keywords = [
    # {'keyword': '低空物流', 'weight': 10},
    # {'keyword': '低空经济', 'weight': 10},
    # {'keyword': 'eVTOL', 'weight': 10},
    # {'keyword': '低空医疗', 'weight': 10},
    # {'keyword': '低空出行', 'weight': 10},
    # {'keyword': '低空交通', 'weight': 8},
]

# Topic = 低空经济 in 百度资讯
low_altitude_economy_baidunews_keywords = [
    # {'keyword': '低空物流', 'weight': 10},
    # {'keyword': '低空经济', 'weight': 10},
    # {'keyword': 'eVTOL', 'weight': 10},
    # {'keyword': '低空医疗', 'weight': 10},
    # {'keyword': '低空出行', 'weight': 10},
    # {'keyword': '低空交通', 'weight': 8},
]

# Topic = 商业航天 in 头条资讯
commercial_space_toutiaonews_keywords = [
    # {'keyword': '商业航天', 'weight': 9.5},
    # {'keyword': '星舰', 'weight': 10},
    # {'keyword': 'star ship', 'weight': 10},
    # {'keyword': '星链', 'weight': 9.5},
    # {'keyword': 'star link', 'weight': 10},
    # {'keyword': '猎鹰火箭', 'weight': 10},
    # {'keyword': '猎鹰9号', 'weight': 10},
    # {'keyword': '猎鹰重型', 'weight': 10},
    # {'keyword': 'spacex', 'weight': 9.0},
    # {'keyword': '卫星互联网', 'weight': 9.0},
    # {'keyword': '低轨卫星', 'weight': 9.0},
    # {'keyword': '中国卫星通信集团', 'weight': 8},
    # {'keyword': '中国卫通', 'weight': 8},
    # {'keyword': '上海微小卫星', 'weight': 8},
    # {'keyword': '航天长峰', 'weight': 8},
    # {'keyword': '长峰航天', 'weight': 8},
    # {'keyword': '银河航天', 'weight': 8},
    # {'keyword': '银河互联网', 'weight': 8},
    # {'keyword': 'Galactic Network', 'weight': 8},
    # {'keyword': '蓝箭', 'weight': 10},
    # {'keyword': 'LandSpace', 'weight': 8},
    # {'keyword': '星际荣耀', 'weight': 10},
    # {'keyword': 'iSpace', 'weight': 8},
    # {'keyword': '零壹空间', 'weight': 10},
    # {'keyword': 'OneSpace', 'weight': 8},
    # {'keyword': '中科微星', 'weight': 7},
    # {'keyword': '星网', 'weight': 9},
    # {'keyword': 'China Satellite Network', 'weight': 9},
    # {'keyword': '鸿雁星座', 'weight': 8},
    # {'keyword': '虹云', 'weight': 8},
    # {'keyword': '快舟', 'weight': 8},
]

# Topic = 商业航天 in 百度资讯
commercial_space_baidunews_keywords = [
    # {'keyword': '商业航天', 'weight': 9.5},
    # {'keyword': '星舰', 'weight': 10},
    # {'keyword': 'star ship', 'weight': 10},
    # {'keyword': '星链', 'weight': 9.5},
    # {'keyword': 'star link', 'weight': 10},
    # {'keyword': '猎鹰火箭', 'weight': 10},
    # {'keyword': '猎鹰9号', 'weight': 10},
    # {'keyword': '猎鹰重型', 'weight': 10},
    # {'keyword': 'spacex', 'weight': 9.0},
    # {'keyword': '卫星互联网', 'weight': 9.0},
    # {'keyword': '低轨卫星', 'weight': 9.0},
    # {'keyword': '中国卫星通信集团', 'weight': 8},
    # {'keyword': '中国卫通', 'weight': 8},
    # {'keyword': '上海微小卫星', 'weight': 8},
    # {'keyword': '航天长峰', 'weight': 8},
    # {'keyword': '长峰航天', 'weight': 8},
    # {'keyword': '银河航天', 'weight': 8},
    # {'keyword': '银河互联网', 'weight': 8},
    # {'keyword': 'Galactic Network', 'weight': 8},
    # {'keyword': '蓝箭', 'weight': 10},
    # {'keyword': 'LandSpace', 'weight': 8},
    # {'keyword': '星际荣耀', 'weight': 10},
    # {'keyword': 'iSpace', 'weight': 8},
    # {'keyword': '零壹空间', 'weight': 10},
    # {'keyword': 'OneSpace', 'weight': 8},
    # {'keyword': '中科微星', 'weight': 7},
    # {'keyword': '星网', 'weight': 9},
    # {'keyword': 'China Satellite Network', 'weight': 9},
    # {'keyword': '鸿雁星座', 'weight': 8},
    # {'keyword': '虹云', 'weight': 8},
    # {'keyword': '快舟', 'weight': 8},
]

# Topic = 生物制造 in 头条资讯
Biomanufacturing_toutiaonews_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    # {'keyword': '合成生物', 'weight': 10},
    # {'keyword': 'bio-made', 'weight': 10},
    # {'keyword': 'SynBio', 'weight': 10},
    # {'keyword': '合成蛋白质', 'weight': 10},
    # {'keyword': '蛋白质合成', 'weight': 10},
    # {'keyword': '人造肉', 'weight': 10},
    # {'keyword': '多组学', 'weight': 10},
    # {'keyword': 'AlphaFold', 'weight': 10},
    # {'keyword': 'AI药物', 'weight': 10},
    # {'keyword': 'AI制药', 'weight': 10},
    # {'keyword': 'AI蛋白质', 'weight': 10},
    # {'keyword': '蔚蓝生物', 'weight': 10},
    # {'keyword': '播恩', 'weight': 10},
    # {'keyword': '圣达', 'weight': 10},
    # {'keyword': '亚香股份', 'weight': 10},
    # {'keyword': '凯赛', 'weight': 10},
    # {'keyword': '溢多利', 'weight': 10},
    # {'keyword': '金城医药', 'weight': 10},
    # {'keyword': '鲁抗医药', 'weight': 10},
    # {'keyword': '梅花生物', 'weight': 10},
    # {'keyword': '富士莱', 'weight': 10},
    # {'keyword': '翰宇药业', 'weight': 10},
    # {'keyword': '瀚科迈博', 'weight': 10},
    # {'keyword': '嘉必优', 'weight': 10},
    # {'keyword': '川宁', 'weight': 10},
    # {'keyword': '凯莱英', 'weight': 10},
    # {'keyword': '沃特', 'weight': 10},
    # {'keyword': '震元', 'weight': 10},
    # {'keyword': '朗坤', 'weight': 10},
    # {'keyword': '宇道', 'weight': 10},
    # {'keyword': '酶赛', 'weight': 10},
    # {'keyword': '恩凯赛药', 'weight': 10},
    # {'keyword': '昌进生物', 'weight': 10},
    # {'keyword': '食未科技', 'weight': 10},
    # {'keyword': '柯泰亚', 'weight': 10},
    # {'keyword': '贻如生物', 'weight': 10},
    # {'keyword': '迪赛诺', 'weight': 10},
    # {'keyword': '羽冠生物', 'weight': 10},
    # {'keyword': '奔耀科技', 'weight': 10},
    # {'keyword': '玄刃科技', 'weight': 10},
    # {'keyword': '康码生物', 'weight': 10},
    # {'keyword': '翌圣', 'weight': 10},
    # {'keyword': '镁孚泰', 'weight': 10},
    # {'keyword': '迪赢生物', 'weight': 10},
    # {'keyword': '正序生物', 'weight': 10},
    # {'keyword': '青莲百奥', 'weight': 10},
    # {'keyword': '惠利生物', 'weight': 10},
    # {'keyword': '百葵锐', 'weight': 10},
    # {'keyword': '天境', 'weight': 10},
    # {'keyword': '百图生科', 'weight': 10},
    # {'keyword': '西湖欧米', 'weight': 10},
    # {'keyword': '普美瑞', 'weight': 10},
    # {'keyword': '引加', 'weight': 10},
    # {'keyword': '智峪生科', 'weight': 10},
    # {'keyword': '华深智药', 'weight': 10},
    # {'keyword': '百奥几何', 'weight': 10},
    # {'keyword': '天擎科技', 'weight': 10},
    # {'keyword': '珞米', 'weight': 10},
    # {'keyword': '力文所', 'weight': 10},
    # {'keyword': '分子之心', 'weight': 10},
    # {'keyword': '橙影', 'weight': 10},
    # {'keyword': '城新说', 'weight': 10},
    # {'keyword': '呈元科技', 'weight': 10},
    # {'keyword': '途深智合', 'weight': 10},
    # {'keyword': '酶促DNA', 'weight': 10},
    # {'keyword': '甜味蛋白', 'weight': 10},
    # {'keyword': '英矽智能', 'weight': 10},
    # {'keyword': '寻百会', 'weight': 10},
    # {'keyword': '水木未来', 'weight': 10},
    # {'keyword': '红云生物', 'weight': 10},
    # {'keyword': '燃坤智能', 'weight': 10},
    # {'keyword': '亿药科技', 'weight': 10},
    # {'keyword': '英飞智药', 'weight': 10},
    # {'keyword': '百奥智汇', 'weight': 10},
    # {'keyword': '劲风生物', 'weight': 10},
    # {'keyword': '双运生物', 'weight': 10},
    # {'keyword': '西湖云谷', 'weight': 10},
    # {'keyword': '莱芒生物', 'weight': 10},
    # {'keyword': '数因信科', 'weight': 10},
    # {'keyword': '天鹭科技', 'weight': 10},
    # {'keyword': '医图生科', 'weight': 10},
    # {'keyword': '高维医药', 'weight': 10},
    # {'keyword': 'Aureka', 'weight': 10},
    # {'keyword': 'Biotech', 'weight': 10},
    # {'keyword': '寻鲸生科', 'weight': 10},
    # {'keyword': '水木分子', 'weight': 10},
    # {'keyword': '哲源科技', 'weight': 10},
    # {'keyword': '阿尔脉生物', 'weight': 10},
    # {'keyword': '青云瑞晶', 'weight': 10},
    # {'keyword': '超维知药', 'weight': 10},
    # {'keyword': '阿尔法分子', 'weight': 10},
    # {'keyword': '康迈迪森', 'weight': 10},
    # {'keyword': '圆壹智慧', 'weight': 10},
    # {'keyword': '新樾生物', 'weight': 10},
    # {'keyword': '佩德生物', 'weight': 10},
    # {'keyword': '益杰立科', 'weight': 10},
    # {'keyword': '标智未来', 'weight': 10},
    # {'keyword': '晶泰科技', 'weight': 10},
    # {'keyword': '冰洲石生物', 'weight': 10},
    # {'keyword': '新合生物', 'weight': 10},
    # {'keyword': '未知君', 'weight': 10},
    # {'keyword': '智药科技', 'weight': 10},
    # {'keyword': '星亢原生物', 'weight': 10},
    # {'keyword': '深势科技', 'weight': 10},
    # {'keyword': '星药科技', 'weight': 10},
    # {'keyword': '剂泰医药', 'weight': 10},
    # {'keyword': '耀生物', 'weight': 10},
    # {'keyword': '希格生科', 'weight': 10},
    # {'keyword': '沃时科技', 'weight': 10},
    # {'keyword': '玄言生物', 'weight': 10},
    # {'keyword': '默达生物', 'weight': 10},
    # {'keyword': '元星智药', 'weight': 10},
    # {'keyword': '影粒生物', 'weight': 10},
    # {'keyword': '域新说', 'weight': 10},
    # {'keyword': '衡昱生物', 'weight': 10},
    # {'keyword': '中大唯信', 'weight': 10},
    # {'keyword': '药物牧场', 'weight': 10},
    # {'keyword': '胜普泽泰', 'weight': 10},
    # {'keyword': '容健医药', 'weight': 10},
    # {'keyword': '深度智耀', 'weight': 10},
    # {'keyword': '角井生物', 'weight': 10},
    # {'keyword': '智容医药', 'weight': 10},
    # {'keyword': '锐格医药', 'weight': 10},
    # {'keyword': '智化科技', 'weight': 10},
    # {'keyword': '大湾生物', 'weight': 10},
    # {'keyword': '信华生物', 'weight': 10},
    # {'keyword': '埃格林医药', 'weight': 10},
    # {'keyword': 'MEDI', 'weight': 10},
    # {'keyword': '德容智药', 'weight': 10},
    # {'keyword': '索智生物', 'weight': 10},
    # {'keyword': '朗容生物', 'weight': 10},
    # {'keyword': '溪砾科技', 'weight': 10},
    # {'keyword': '雅深智慧', 'weight': 10},
    # {'keyword': '立妙达', 'weight': 10},
    # {'keyword': '爱信智耀', 'weight': 10},
    # {'keyword': 'EIHealth', 'weight': 10},
    # {'keyword': '云深智药', 'weight': 10},
    # {'keyword': '普瑞基准', 'weight': 10},
    # {'keyword': '湃隆生物', 'weight': 10},
    # {'keyword': '科辉智药', 'weight': 10},
    # {'keyword': '科因生物', 'weight': 10},
    # {'keyword': 'EDICINE', 'weight': 10},
    # {'keyword': '科镁联', 'weight': 10},
    # {'keyword': 'Ensem', 'weight': 10},
    # {'keyword': '腾迈医药', 'weight': 10},
    # {'keyword': '望石智慧', 'weight': 10},
    # {'keyword': '费米子', 'weight': 10},
    # {'keyword': '焕一生物', 'weight': 10},
    # {'keyword': '中以海德', 'weight': 10},
    # {'keyword': '碳硅智慧', 'weight': 10},
]

# Topic = 生物制造 in 百度资讯
Biomanufacturing_baidunews_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    # {'keyword': '合成生物', 'weight': 10},
    # {'keyword': 'bio-made', 'weight': 10},
    # {'keyword': 'SynBio', 'weight': 10},
    # {'keyword': '合成蛋白质', 'weight': 10},
    # {'keyword': '蛋白质合成', 'weight': 10},
    # {'keyword': '人造肉', 'weight': 10},
    # {'keyword': '多组学', 'weight': 10},
    # {'keyword': 'AlphaFold', 'weight': 10},
    # {'keyword': 'AI药物', 'weight': 10},
    # {'keyword': 'AI制药', 'weight': 10},
    # {'keyword': 'AI蛋白质', 'weight': 10},
    # {'keyword': '蔚蓝生物', 'weight': 10},
    # {'keyword': '播恩', 'weight': 10},
    # {'keyword': '圣达', 'weight': 10},
    # {'keyword': '亚香股份', 'weight': 10},
    # {'keyword': '凯赛', 'weight': 10},
    # {'keyword': '溢多利', 'weight': 10},
    # {'keyword': '金城医药', 'weight': 10},
    # {'keyword': '鲁抗医药', 'weight': 10},
    # {'keyword': '梅花生物', 'weight': 10},
    # {'keyword': '富士莱', 'weight': 10},
    # {'keyword': '翰宇药业', 'weight': 10},
    # {'keyword': '瀚科迈博', 'weight': 10},
    # {'keyword': '嘉必优', 'weight': 10},
    # {'keyword': '川宁', 'weight': 10},
    # {'keyword': '凯莱英', 'weight': 10},
    # {'keyword': '沃特', 'weight': 10},
    # {'keyword': '震元', 'weight': 10},
    # {'keyword': '朗坤', 'weight': 10},
    # {'keyword': '宇道', 'weight': 10},
    # {'keyword': '酶赛', 'weight': 10},
    # {'keyword': '恩凯赛药', 'weight': 10},
    # {'keyword': '昌进生物', 'weight': 10},
    # {'keyword': '食未科技', 'weight': 10},
    # {'keyword': '柯泰亚', 'weight': 10},
    # {'keyword': '贻如生物', 'weight': 10},
    # {'keyword': '迪赛诺', 'weight': 10},
    # {'keyword': '羽冠生物', 'weight': 10},
    # {'keyword': '奔耀科技', 'weight': 10},
    # {'keyword': '玄刃科技', 'weight': 10},
    # {'keyword': '康码生物', 'weight': 10},
    # {'keyword': '翌圣', 'weight': 10},
    # {'keyword': '镁孚泰', 'weight': 10},
    # {'keyword': '迪赢生物', 'weight': 10},
    # {'keyword': '正序生物', 'weight': 10},
    # {'keyword': '青莲百奥', 'weight': 10},
    # {'keyword': '惠利生物', 'weight': 10},
    # {'keyword': '百葵锐', 'weight': 10},
    # {'keyword': '天境', 'weight': 10},
    # {'keyword': '百图生科', 'weight': 10},
    # {'keyword': '西湖欧米', 'weight': 10},
    # {'keyword': '普美瑞', 'weight': 10},
    # {'keyword': '引加', 'weight': 10},
    # {'keyword': '智峪生科', 'weight': 10},
    # {'keyword': '华深智药', 'weight': 10},
    # {'keyword': '百奥几何', 'weight': 10},
    # {'keyword': '天擎科技', 'weight': 10},
    # {'keyword': '珞米', 'weight': 10},
    # {'keyword': '力文所', 'weight': 10},
    # {'keyword': '分子之心', 'weight': 10},
    # {'keyword': '橙影', 'weight': 10},
    # {'keyword': '城新说', 'weight': 10},
    # {'keyword': '呈元科技', 'weight': 10},
    # {'keyword': '途深智合', 'weight': 10},
    # {'keyword': '酶促DNA', 'weight': 10},
    # {'keyword': '甜味蛋白', 'weight': 10},
    # {'keyword': '英矽智能', 'weight': 10},
    # {'keyword': '寻百会', 'weight': 10},
    # {'keyword': '水木未来', 'weight': 10},
    # {'keyword': '红云生物', 'weight': 10},
    # {'keyword': '燃坤智能', 'weight': 10},
    # {'keyword': '亿药科技', 'weight': 10},
    # {'keyword': '英飞智药', 'weight': 10},
    # {'keyword': '百奥智汇', 'weight': 10},
    # {'keyword': '劲风生物', 'weight': 10},
    # {'keyword': '双运生物', 'weight': 10},
    # {'keyword': '西湖云谷', 'weight': 10},
    # {'keyword': '莱芒生物', 'weight': 10},
    # {'keyword': '数因信科', 'weight': 10},
    # {'keyword': '天鹭科技', 'weight': 10},
    # {'keyword': '医图生科', 'weight': 10},
    # {'keyword': '高维医药', 'weight': 10},
    # {'keyword': 'Aureka', 'weight': 10},
    # {'keyword': 'Biotech', 'weight': 10},
    # {'keyword': '寻鲸生科', 'weight': 10},
    # {'keyword': '水木分子', 'weight': 10},
    # {'keyword': '哲源科技', 'weight': 10},
    # {'keyword': '阿尔脉生物', 'weight': 10},
    # {'keyword': '青云瑞晶', 'weight': 10},
    # {'keyword': '超维知药', 'weight': 10},
    # {'keyword': '阿尔法分子', 'weight': 10},
    # {'keyword': '康迈迪森', 'weight': 10},
    # {'keyword': '圆壹智慧', 'weight': 10},
    # {'keyword': '新樾生物', 'weight': 10},
    # {'keyword': '佩德生物', 'weight': 10},
    # {'keyword': '益杰立科', 'weight': 10},
    # {'keyword': '标智未来', 'weight': 10},
    # {'keyword': '晶泰科技', 'weight': 10},
    # {'keyword': '冰洲石生物', 'weight': 10},
    # {'keyword': '新合生物', 'weight': 10},
    # {'keyword': '未知君', 'weight': 10},
    # {'keyword': '智药科技', 'weight': 10},
    # {'keyword': '星亢原生物', 'weight': 10},
    # {'keyword': '深势科技', 'weight': 10},
    # {'keyword': '星药科技', 'weight': 10},
    # {'keyword': '剂泰医药', 'weight': 10},
    # {'keyword': '耀生物', 'weight': 10},
    # {'keyword': '希格生科', 'weight': 10},
    # {'keyword': '沃时科技', 'weight': 10},
    # {'keyword': '玄言生物', 'weight': 10},
    # {'keyword': '默达生物', 'weight': 10},
    # {'keyword': '元星智药', 'weight': 10},
    # {'keyword': '影粒生物', 'weight': 10},
    # {'keyword': '域新说', 'weight': 10},
    # {'keyword': '衡昱生物', 'weight': 10},
    # {'keyword': '中大唯信', 'weight': 10},
    # {'keyword': '药物牧场', 'weight': 10},
    # {'keyword': '胜普泽泰', 'weight': 10},
    # {'keyword': '容健医药', 'weight': 10},
    # {'keyword': '深度智耀', 'weight': 10},
    # {'keyword': '角井生物', 'weight': 10},
    # {'keyword': '智容医药', 'weight': 10},
    # {'keyword': '锐格医药', 'weight': 10},
    # {'keyword': '智化科技', 'weight': 10},
    # {'keyword': '大湾生物', 'weight': 10},
    # {'keyword': '信华生物', 'weight': 10},
    # {'keyword': '埃格林医药', 'weight': 10},
    # {'keyword': 'MEDI', 'weight': 10},
    # {'keyword': '德容智药', 'weight': 10},
    # {'keyword': '索智生物', 'weight': 10},
    # {'keyword': '朗容生物', 'weight': 10},
    # {'keyword': '溪砾科技', 'weight': 10},
    # {'keyword': '雅深智慧', 'weight': 10},
    # {'keyword': '立妙达', 'weight': 10},
    # {'keyword': '爱信智耀', 'weight': 10},
    # {'keyword': 'EIHealth', 'weight': 10},
    # {'keyword': '云深智药', 'weight': 10},
    # {'keyword': '普瑞基准', 'weight': 10},
    # {'keyword': '湃隆生物', 'weight': 10},
    # {'keyword': '科辉智药', 'weight': 10},
    # {'keyword': '科因生物', 'weight': 10},
    # {'keyword': 'EDICINE', 'weight': 10},
    # {'keyword': '科镁联', 'weight': 10},
    # {'keyword': 'Ensem', 'weight': 10},
    # {'keyword': '腾迈医药', 'weight': 10},
    # {'keyword': '望石智慧', 'weight': 10},
    # {'keyword': '费米子', 'weight': 10},
    # {'keyword': '焕一生物', 'weight': 10},
    # {'keyword': '中以海德', 'weight': 10},
    # {'keyword': '碳硅智慧', 'weight': 10},
]

# Topic = 先锋热点 in 头条资讯
HotPoint_toutiaonews_keywords = [
    {'keyword': '贝森特', 'weight': 10},
    {'keyword': 'Bessent', 'weight': 10},
    {'keyword': '马斯克', 'weight': 10},
    {'keyword': 'elon musk', 'weight': 10},
    {'keyword': '雷军', 'weight': 9},
    {'keyword': '雷总', 'weight': 9},
]

# Topic = 先锋热点 in 百度资讯
HotPoint_baidunews_keywords = [
    {'keyword': '贝森特', 'weight': 10},
    {'keyword': 'Bessent', 'weight': 10},
    {'keyword': '马斯克', 'weight': 10},
    {'keyword': 'elon musk', 'weight': 10},
    {'keyword': '雷军', 'weight': 9},
    {'keyword': '雷总', 'weight': 9},
]

# Topic = AI算力 in 头条资讯
AIHPC_toutiaonews_keywords = [
]

# Topic = AI算力 in 百度资讯
AIHPC_baidunews_keywords = [
]

# Topic = 激光雷达 in 头条资讯
LidarADAS_toutiaonews_keywords = [
    {'keyword': 'FMCW', 'weight': 10},
    {'keyword': 'OPA', 'weight': 10},
    {'keyword': '禾赛', 'weight': 10},
    {'keyword': '速腾', 'weight': 10},
    {'keyword': 'robosense', 'weight': 10},
    {'keyword': 'hesai', 'weight': 10},
    {'keyword': '图达通', 'weight': 10},
    {'keyword': '华为激光雷达', 'weight': 10},
    {'keyword': '华为自研激光雷达', 'weight': 10},
    {'keyword': '一径', 'weight': 10},
    {'keyword': '大疆览沃', 'weight': 10},
    {'keyword': '北醒', 'weight': 10},
    {'keyword': '探维', 'weight': 10},
    {'keyword': '洛微', 'weight': 10},
    {'keyword': '摩尔芯光', 'weight': 10},
    {'keyword': '万集科技', 'weight': 10},
    {'keyword': '长光华芯', 'weight': 10},
    {'keyword': '芯视界', 'weight': 10},
    {'keyword': '阜时', 'weight': 10},
    {'keyword': '识光', 'weight': 10},
    {'keyword': '纵慧芯光', 'weight': 10},
    {'keyword': 'Luminar', 'weight': 10},
    {'keyword': 'Aeva', 'weight': 10},
    {'keyword': 'Ouster', 'weight': 10},
]



# Topic = 激光雷达 in 百度资讯
LidarADAS_baidunews_keywords = [
    {'keyword': 'FMCW', 'weight': 10},
    {'keyword': 'OPA', 'weight': 10},
    {'keyword': '禾赛', 'weight': 10},
    {'keyword': '速腾', 'weight': 10},
    {'keyword': 'robosense', 'weight': 10},
    {'keyword': 'hesai', 'weight': 10},
    {'keyword': '图达通', 'weight': 10},
    {'keyword': '华为激光雷达', 'weight': 10},
    {'keyword': '华为自研激光雷达', 'weight': 10},
    {'keyword': '一径', 'weight': 10},
    {'keyword': '大疆览沃', 'weight': 10},
    {'keyword': '北醒', 'weight': 10},
    {'keyword': '探维', 'weight': 10},
    {'keyword': '洛微', 'weight': 10},
    {'keyword': '摩尔芯光', 'weight': 10},
    {'keyword': '万集科技', 'weight': 10},
    {'keyword': '长光华芯', 'weight': 10},
    {'keyword': '芯视界', 'weight': 10},
    {'keyword': '阜时', 'weight': 10},
    {'keyword': '识光', 'weight': 10},
    {'keyword': '纵慧芯光', 'weight': 10},
    {'keyword': 'Luminar', 'weight': 10},
    {'keyword': 'Aeva', 'weight': 10},
    {'keyword': 'Ouster', 'weight': 10},
]

# Topic = 量化 in 头条资讯
quantitative_trading_toutiaonews_keywords = [
    # {'keyword': '量化', 'weight': 10},
    {'keyword': '程序化交易', 'weight': 10},
    # {'keyword': '转融通', 'weight': 10},
    # {'keyword': '对冲基金', 'weight': 10},
    # {'keyword': '量化私募', 'weight': 10},
    # {'keyword': '量化基金', 'weight': 10},
    # {'keyword': '量化交易', 'weight': 10},
    # {'keyword': 'dma量化交易', 'weight': 10},
    # {'keyword': '高频交易', 'weight': 10},
    # {'keyword': 'smart beta', 'weight': 10},
    # {'keyword': 'smart贝塔', 'weight': 10},
    # {'keyword': 'smart β', 'weight': 10},
    # {'keyword': 'etf套利', 'weight': 10},
    # {'keyword': '宽基对冲', 'weight': 10},
    # {'keyword': '跨品种套利', 'weight': 8},
    # # {'keyword': '量化选股', 'weight': 8},
    # # {'keyword': '量化择时', 'weight': 8},
    # {'keyword': '指数增强', 'weight': 6},
    # {'keyword': '指增', 'weight': 6},
    # {'keyword': '均值回复', 'weight': 7},
    # {'keyword': '幻方量化', 'weight': 10},
    # {'keyword': '明汯量化', 'weight': 10},
    # {'keyword': '灵均量化', 'weight': 10},
    # {'keyword': '九坤量化', 'weight': 10},
    # {'keyword': '衍复量化', 'weight': 10},
    # {'keyword': '天演量化', 'weight': 10},
    # {'keyword': '卓识量化', 'weight': 10},
    # {'keyword': '稳博量化', 'weight': 10},
    # {'keyword': '宽德量化', 'weight': 10},
    # {'keyword': '诚奇量化', 'weight': 10},
    # {'keyword': '金锝量化', 'weight': 10},
    # {'keyword': '启林量化', 'weight': 10},
    # {'keyword': '茂源量化', 'weight': 10},
    # {'keyword': '金戈量锐', 'weight': 10},
    # {'keyword': '黑翼量化', 'weight': 10},
    # {'keyword': '信弘天禾', 'weight': 10},
    # {'keyword': '思勰量化', 'weight': 10},
    # {'keyword': '呜石量化', 'weight': 10},
    # {'keyword': '锐天量化', 'weight': 10},
    # {'keyword': '龙旗科技', 'weight': 10},
    # {'keyword': '进化论量化', 'weight': 10},
    # {'keyword': '宽产量化', 'weight': 10},
    # {'keyword': '博普量化', 'weight': 10},
    # {'keyword': '赫富量化', 'weight': 10},
    # {'keyword': '涵德量化', 'weight': 10},
    # {'keyword': '国恩量化', 'weight': 10},
    # {'keyword': '艾方量化', 'weight': 10},
    # {'keyword': '星瑞量化', 'weight': 10},
    # {'keyword': '白鹭量化', 'weight': 10},
    # {'keyword': '因诺量化', 'weight': 10},
    # {'keyword': '凯纳量化', 'weight': 10},
    # {'keyword': '念空念觉量化', 'weight': 10},
    # {'keyword': '千象量化', 'weight': 10},
    # {'keyword': '洛书量化', 'weight': 10},
    # {'keyword': '蒙玺量化', 'weight': 10},
    # {'keyword': '千宜量化', 'weight': 10},
    # {'keyword': '平方和量化', 'weight': 10},
    # {'keyword': '申毅量化', 'weight': 10},
    # {'keyword': '心汉页习', 'weight': 10},
    # {'keyword': '乾象量化', 'weight': 10},
    # {'keyword': '盛冠达量化', 'weight': 10},
    # {'keyword': '思晔量化', 'weight': 10},
    # {'keyword': '天算量化', 'weight': 10},
    # {'keyword': '图灵量化', 'weight': 10},
    # {'keyword': '衍盛量化', 'weight': 10},
    # {'keyword': '象限量化', 'weight': 10},
    # {'keyword': '展弘量化', 'weight': 10},
    # {'keyword': '仲阳天王量化', 'weight': 10},
    # {'keyword': '顽岩量化', 'weight': 10},
    # {'keyword': '致诚卓远', 'weight': 10},
]

# Topic = 量化 in 百度资讯
quantitative_trading_baidunews_keywords = [
# {'keyword': '量化', 'weight': 10},
    {'keyword': '程序化交易', 'weight': 10},
    # {'keyword': '转融通', 'weight': 10},
    # {'keyword': '对冲基金', 'weight': 10},
    # {'keyword': '量化私募', 'weight': 10},
    # {'keyword': '量化基金', 'weight': 10},
    # {'keyword': '量化交易', 'weight': 10},
    # {'keyword': 'dma量化交易', 'weight': 10},
    # {'keyword': '高频交易', 'weight': 10},
    # {'keyword': 'smart beta', 'weight': 10},
    # {'keyword': 'smart贝塔', 'weight': 10},
    # {'keyword': 'smart β', 'weight': 10},
    # {'keyword': 'etf套利', 'weight': 10},
    # {'keyword': '宽基对冲', 'weight': 10},
    # {'keyword': '跨品种套利', 'weight': 8},
    # # {'keyword': '量化选股', 'weight': 8},
    # # {'keyword': '量化择时', 'weight': 8},
    # {'keyword': '指数增强', 'weight': 6},
    # {'keyword': '指增', 'weight': 6},
    # {'keyword': '均值回复', 'weight': 7},
    # {'keyword': '幻方量化', 'weight': 10},
    # {'keyword': '明汯量化', 'weight': 10},
    # {'keyword': '灵均量化', 'weight': 10},
    # {'keyword': '九坤量化', 'weight': 10},
    # {'keyword': '衍复量化', 'weight': 10},
    # {'keyword': '天演量化', 'weight': 10},
    # {'keyword': '卓识量化', 'weight': 10},
    # {'keyword': '稳博量化', 'weight': 10},
    # {'keyword': '宽德量化', 'weight': 10},
    # {'keyword': '诚奇量化', 'weight': 10},
    # {'keyword': '金锝量化', 'weight': 10},
    # {'keyword': '启林量化', 'weight': 10},
    # {'keyword': '茂源量化', 'weight': 10},
    # {'keyword': '金戈量锐', 'weight': 10},
    # {'keyword': '黑翼量化', 'weight': 10},
    # {'keyword': '信弘天禾', 'weight': 10},
    # {'keyword': '思勰量化', 'weight': 10},
    # {'keyword': '呜石量化', 'weight': 10},
    # {'keyword': '锐天量化', 'weight': 10},
    # {'keyword': '龙旗科技', 'weight': 10},
    # {'keyword': '进化论量化', 'weight': 10},
    # {'keyword': '宽产量化', 'weight': 10},
    # {'keyword': '博普量化', 'weight': 10},
    # {'keyword': '赫富量化', 'weight': 10},
    # {'keyword': '涵德量化', 'weight': 10},
    # {'keyword': '国恩量化', 'weight': 10},
    # {'keyword': '艾方量化', 'weight': 10},
    # {'keyword': '星瑞量化', 'weight': 10},
    # {'keyword': '白鹭量化', 'weight': 10},
    # {'keyword': '因诺量化', 'weight': 10},
    # {'keyword': '凯纳量化', 'weight': 10},
    # {'keyword': '念空念觉量化', 'weight': 10},
    # {'keyword': '千象量化', 'weight': 10},
    # {'keyword': '洛书量化', 'weight': 10},
    # {'keyword': '蒙玺量化', 'weight': 10},
    # {'keyword': '千宜量化', 'weight': 10},
    # {'keyword': '平方和量化', 'weight': 10},
    # {'keyword': '申毅量化', 'weight': 10},
    # {'keyword': '心汉页习', 'weight': 10},
    # {'keyword': '乾象量化', 'weight': 10},
    # {'keyword': '盛冠达量化', 'weight': 10},
    # {'keyword': '思晔量化', 'weight': 10},
    # {'keyword': '天算量化', 'weight': 10},
    # {'keyword': '图灵量化', 'weight': 10},
    # {'keyword': '衍盛量化', 'weight': 10},
    # {'keyword': '象限量化', 'weight': 10},
    # {'keyword': '展弘量化', 'weight': 10},
    # {'keyword': '仲阳天王量化', 'weight': 10},
    # {'keyword': '顽岩量化', 'weight': 10},
    # {'keyword': '致诚卓远', 'weight': 10},
]