# # 关键词列表,每个元素是一个字典,包含关键词和对应权重


# Topic = 低空经济
low_altitude_economy_keywords = [
    {'keyword': '低空物流', 'weight': 10},
    {'keyword': '低空经济', 'weight': 10},
    {'keyword': 'eVTOL', 'weight': 10},
    {'keyword': '低空医疗', 'weight': 10},
    {'keyword': '低空航线', 'weight': 10},
    {'keyword': '低空出行', 'weight': 10},
    {'keyword': '低小慢', 'weight': 10},
    {'keyword': '垂直起降', 'weight': 8},
    {'keyword': '空中交通', 'weight': 8},
    {'keyword': '低空飞行器', 'weight': 8},
    {'keyword': '智能飞行', 'weight': 8},
]

# Topic = 商业航天
commercial_space_keywords = [
    {'keyword': '商业航天', 'weight': 9.5},
    {'keyword': '星舰', 'weight': 10},
    {'keyword': 'star ship', 'weight': 10},
    {'keyword': '星链', 'weight': 9.5},
    {'keyword': 'star link', 'weight': 10},
    {'keyword': '猎鹰火箭', 'weight': 10},
    {'keyword': '猎鹰9号', 'weight': 10},
    {'keyword': '猎鹰重型', 'weight': 10},
    {'keyword': 'spacex', 'weight': 9.0},
    {'keyword': '运载火箭', 'weight': 9.5},
    {'keyword': '卫星互联网', 'weight': 9.0},
    {'keyword': '低轨', 'weight': 9.0},
    {'keyword': '中国卫星通信集团', 'weight': 8},
    {'keyword': '中国卫通', 'weight': 8},
    {'keyword': '上海微小卫星', 'weight': 8},
    {'keyword': 'SMIC', 'weight': 8},
    {'keyword': '航天长峰', 'weight': 8},
    {'keyword': '长峰航天', 'weight': 8},
    {'keyword': '银河航天', 'weight': 8},
    {'keyword': '银河互联网', 'weight': 8},
    {'keyword': 'Galactic Network', 'weight': 8},
    {'keyword': '蓝箭', 'weight': 10},
    {'keyword': 'LandSpace', 'weight': 8},
    {'keyword': '星际荣耀', 'weight': 10},
    {'keyword': 'iSpace', 'weight': 8},
    {'keyword': '零壹', 'weight': 10},
    {'keyword': 'OneSpace', 'weight': 8},
    {'keyword': '中科微星', 'weight': 7},
    {'keyword': '天仪研究院', 'weight': 7},
    {'keyword': '天仪', 'weight': 7},
    {'keyword': 'Spacety', 'weight': 7},
    {'keyword': '星网', 'weight': 9},
    {'keyword': 'China Satellite Network', 'weight': 9},
    {'keyword': '鸿雁星座', 'weight': 8},
    {'keyword': '鸿雁', 'weight': 8},
    {'keyword': '虹云', 'weight': 8},
    {'keyword': '快舟', 'weight': 8},
]

# Topic = 通用价值点
common_value_keywords = [
    {'keyword': '加群', 'weight': 10},
    {'keyword': '该二维码7天内', 'weight': 10},
    {'keyword': '入群', 'weight': 10},
    {'keyword': '微信群', 'weight': 10},
    {'keyword': '交流群', 'weight': 10},
    {'keyword': '行业群', 'weight': 10},
    {'keyword': '投研群', 'weight': 10},
    # {'keyword': '作者微信', 'weight': 10},
    # {'keyword': '主理人', 'weight': 10},
    # {'keyword': '二维码', 'weight': 10},
    {'keyword': '长按', 'weight': 10},
    {'keyword': '电话会', 'weight': 10},
    {'keyword': '策略会', 'weight': 10},
    {'keyword': '业绩会', 'weight': 10},
    {'keyword': '腾讯会议', 'weight': 10},
    {'keyword': '沙龙', 'weight': 10},
    {'keyword': '讲座', 'weight': 10},
    {'keyword': '峰会', 'weight': 10},
    {'keyword': '交流会', 'weight': 10},
    {'keyword': '研讨会', 'weight': 10},
    {'keyword': '路演', 'weight': 10},
    {'keyword': '超预期', 'weight': 10},
    {'keyword': '预期差', 'weight': 10},
    {'keyword': '梳理', 'weight': 9},
    {'keyword': '产业链梳理', 'weight': 10},
    {'keyword': '测算', 'weight': 10},
    {'keyword': '上险量', 'weight': 10},
]

# Topic = 生物制造
Biomanufacturing_keywords = [
    {'keyword': '生物制造', 'weight': 10},
    {'keyword': '合成生物', 'weight': 10},
    {'keyword': 'SynBio', 'weight': 10},
    {'keyword': 'bio-made', 'weight': 10},
    {'keyword': '蛋白合成', 'weight': 10},
    {'keyword': '蛋白质合成', 'weight': 10},
    {'keyword': '合成蛋白', 'weight': 10},
    {'keyword': '合成蛋白质', 'weight': 10},
    {'keyword': '人造肉', 'weight': 10},
    {'keyword': '多组学', 'weight': 10},
    {'keyword': '蛋白质组学', 'weight': 10},
    {'keyword': 'AlphaFold', 'weight': 10},
    {'keyword': '靶点发现', 'weight': 10},
    {'keyword': '生物标志物', 'weight': 10},
    {'keyword': '构象预测', 'weight': 10},
    {'keyword': '结合模拟', 'weight': 10},
    {'keyword': 'AI药物', 'weight': 10},
    {'keyword': 'AI制药', 'weight': 10},
    {'keyword': 'AI蛋白质', 'weight': 10},
    {'keyword': '难成药靶点', 'weight': 10},
    {'keyword': '变构药物', 'weight': 10},
    {'keyword': '蔚蓝生物', 'weight': 10},
    {'keyword': '播恩', 'weight': 10},
    {'keyword': '圣达', 'weight': 10},
    {'keyword': '亚香股份', 'weight': 10},
    {'keyword': '凯赛', 'weight': 10},
    {'keyword': '溢多利', 'weight': 10},
    {'keyword': '金城医药', 'weight': 10},
    {'keyword': '鲁抗医药', 'weight': 10},
    {'keyword': '梅花生物', 'weight': 10},
    {'keyword': '富士莱', 'weight': 10},
    {'keyword': '翰宇药业', 'weight': 10},
    {'keyword': '瀚科迈博', 'weight': 10},
    {'keyword': '嘉必优', 'weight': 10},
    {'keyword': '川宁', 'weight': 10},
    {'keyword': '凯莱英', 'weight': 10},
    {'keyword': '广济药业', 'weight': 10},
    {'keyword': '沃特', 'weight': 10},
    {'keyword': '震元', 'weight': 10},
    {'keyword': '朗坤', 'weight': 10},
    {'keyword': '宇道', 'weight': 10},
    {'keyword': '酶赛', 'weight': 10},
    {'keyword': '恩凯赛药', 'weight': 10},
    {'keyword': '昌进生物', 'weight': 10},
    {'keyword': '食未科技', 'weight': 10},
    {'keyword': '柯泰亚', 'weight': 10},
    {'keyword': '贻如生物', 'weight': 10},
    {'keyword': '迪赛诺', 'weight': 10},
    {'keyword': '羽冠生物', 'weight': 10},
    {'keyword': '奔耀科技', 'weight': 10},
    {'keyword': '玄刃科技', 'weight': 10},
    {'keyword': '康码生物', 'weight': 10},
    {'keyword': '翌圣', 'weight': 10},
    {'keyword': '镁孚泰', 'weight': 10},
    {'keyword': '迪赢生物', 'weight': 10},
    {'keyword': '正序生物', 'weight': 10},
    {'keyword': '青莲百奥', 'weight': 10},
    {'keyword': '惠利生物', 'weight': 10},
    {'keyword': '百葵锐', 'weight': 10},
    {'keyword': '天境', 'weight': 10},
    {'keyword': '百图生科', 'weight': 10},
    {'keyword': '西湖欧米', 'weight': 10},
    {'keyword': '普美瑞', 'weight': 10},
    {'keyword': '引加', 'weight': 10},
    {'keyword': '智峪生科', 'weight': 10},
    {'keyword': '华深智药', 'weight': 10},
    {'keyword': '百奥几何', 'weight': 10},
    {'keyword': '天擎科技', 'weight': 10},
    {'keyword': '珞米', 'weight': 10},
    {'keyword': '力文所', 'weight': 10},
    {'keyword': '分子之心', 'weight': 10},
    {'keyword': '橙影', 'weight': 10},
    {'keyword': '城新说', 'weight': 10},
    {'keyword': '呈元科技', 'weight': 10},
    {'keyword': '途深智合', 'weight': 10},
    {'keyword': '酶促DNA', 'weight': 10},
    {'keyword': '甜味蛋白', 'weight': 10},
    {'keyword': 'David Baker', 'weight': 10},
    {'keyword': 'Ginkgo', 'weight': 10},
    {'keyword': 'Codexis', 'weight': 10},
    {'keyword': 'Synlogic', 'weight': 10},
    {'keyword': 'Zymergen', 'weight': 10},
    {'keyword': 'Molecular Assemblies', 'weight': 10},
    {'keyword': 'Invizyne', 'weight': 10},
    {'keyword': 'Profluent', 'weight': 10},
    {'keyword': 'Oobli', 'weight': 10},
    {'keyword': 'AbCellera', 'weight': 10},
    {'keyword': 'InterVenn', 'weight': 10},
    {'keyword': 'Genesis Therapeutics', 'weight': 10},
    {'keyword': 'Arzeda', 'weight': 10},
    {'keyword': 'NotCo', 'weight': 10},
    {'keyword': 'Cradle', 'weight': 10},
    {'keyword': 'RevolKa', 'weight': 10},
    {'keyword': 'Olink', 'weight': 10},
    {'keyword': 'Somalogic', 'weight': 10},
    {'keyword': 'Matchpoint', 'weight': 10},
    {'keyword': 'Enzymit', 'weight': 10},
    {'keyword': 'Monod', 'weight': 10},
    {'keyword': 'Rofluent', 'weight': 10},
    {'keyword': 'Juvena Therapeutics', 'weight': 10},
    {'keyword': 'Nabla Bio', 'weight': 10},
    {'keyword': 'BigHat Biosciences', 'weight': 10},
    {'keyword': 'Seismic Therapeutic', 'weight': 10},
    {'keyword': '赛得康', 'weight': 10},
    {'keyword': 'DeepCure', 'weight': 10},
    {'keyword': 'Genesis Therapeutics', 'weight': 10},
    {'keyword': 'Ventus Therapeutics', 'weight': 10},
    {'keyword': '德睿智药', 'weight': 10},
    {'keyword': 'CHARM Therapeutics', 'weight': 10},
    {'keyword': 'Congruence Therapeutics', 'weight': 10},
    {'keyword': 'Gandeeva Therapeutics', 'weight': 10},
    {'keyword': 'ENSEM', 'weight': 10},
    {'keyword': 'Isomorphic Labs', 'weight': 10},
    {'keyword': '予路乾行', 'weight': 10},
    {'keyword': 'Insilico Medicine', 'weight': 10},
    {'keyword': 'Arzeda', 'weight': 10},
    {'keyword': 'Enzymit', 'weight': 10},
    {'keyword': 'Cradle Bio', 'weight': 10},
    {'keyword': 'Monod Bio', 'weight': 10},
    {'keyword': '英矽智能', 'weight': 10},
    {'keyword': '寻百会', 'weight': 10},
    {'keyword': '水木未来', 'weight': 10},
    {'keyword': '红云生物', 'weight': 10},
    {'keyword': '燃坤智能', 'weight': 10},
    {'keyword': '亿药科技', 'weight': 10},
    {'keyword': '英飞智药', 'weight': 10},
    {'keyword': '百奥智汇', 'weight': 10},
    {'keyword': '劲风生物', 'weight': 10},
    {'keyword': '双运生物', 'weight': 10},
    {'keyword': '西湖云谷', 'weight': 10},
    {'keyword': '莱芒生物', 'weight': 10},
    {'keyword': '数因信科', 'weight': 10},
    {'keyword': '天鹭科技', 'weight': 10},
    {'keyword': '医图生科', 'weight': 10},
    {'keyword': '高维医药', 'weight': 10},
    {'keyword': 'Aureka', 'weight': 10},
    {'keyword': 'Biotech', 'weight': 10},
    {'keyword': '寻鲸生科', 'weight': 10},
    {'keyword': '水木分子', 'weight': 10},
    {'keyword': '哲源科技', 'weight': 10},
    {'keyword': '阿尔脉生物', 'weight': 10},
    {'keyword': '青云瑞晶', 'weight': 10},
    {'keyword': '超维知药', 'weight': 10},
    {'keyword': '阿尔法分子', 'weight': 10},
    {'keyword': '康迈迪森', 'weight': 10},
    {'keyword': '圆壹智慧', 'weight': 10},
    {'keyword': '新樾生物', 'weight': 10},
    {'keyword': '佩德生物', 'weight': 10},
    {'keyword': '益杰立科', 'weight': 10},
    {'keyword': '标智未来', 'weight': 10},
    {'keyword': '晶泰科技', 'weight': 10},
    {'keyword': '冰洲石生物', 'weight': 10},
    {'keyword': '新合生物', 'weight': 10},
    {'keyword': '未知君', 'weight': 10},
    {'keyword': '智药科技', 'weight': 10},
    {'keyword': '星亢原生物', 'weight': 10},
    {'keyword': '深势科技', 'weight': 10},
    {'keyword': '星药科技', 'weight': 10},
    {'keyword': '剂泰医药', 'weight': 10},
    {'keyword': '耀生物', 'weight': 10},
    {'keyword': '希格生科', 'weight': 10},
    {'keyword': '沃时科技', 'weight': 10},
    {'keyword': '玄言生物', 'weight': 10},
    {'keyword': '默达生物', 'weight': 10},
    {'keyword': '元星智药', 'weight': 10},
    {'keyword': '影粒生物', 'weight': 10},
    {'keyword': '域新说', 'weight': 10},
    {'keyword': '衡昱生物', 'weight': 10},
    {'keyword': '中大唯信', 'weight': 10},
    {'keyword': '药物牧场', 'weight': 10},
    {'keyword': '胜普泽泰', 'weight': 10},
    {'keyword': '容健医药', 'weight': 10},
    {'keyword': '深度智耀', 'weight': 10},
    {'keyword': '角井生物', 'weight': 10},
    {'keyword': '智容医药', 'weight': 10},
    {'keyword': '锐格医药', 'weight': 10},
    {'keyword': '智化科技', 'weight': 10},
    {'keyword': '大湾生物', 'weight': 10},
    {'keyword': '信华生物', 'weight': 10},
    {'keyword': '埃格林医药', 'weight': 10},
    {'keyword': 'MEDI', 'weight': 10},
    {'keyword': '德容智药', 'weight': 10},
    {'keyword': '索智生物', 'weight': 10},
    {'keyword': '朗容生物', 'weight': 10},
    {'keyword': '溪砾科技', 'weight': 10},
    {'keyword': '雅深智慧', 'weight': 10},
    {'keyword': '立妙达', 'weight': 10},
    {'keyword': '爱信智耀', 'weight': 10},
    {'keyword': 'EIHealth', 'weight': 10},
    {'keyword': '云深智药', 'weight': 10},
    {'keyword': '普瑞基准', 'weight': 10},
    {'keyword': '湃隆生物', 'weight': 10},
    {'keyword': '科辉智药', 'weight': 10},
    {'keyword': '科因生物', 'weight': 10},
    {'keyword': 'EDICINE', 'weight': 10},
    {'keyword': '科镁联', 'weight': 10},
    {'keyword': 'Ensem', 'weight': 10},
    {'keyword': '腾迈医药', 'weight': 10},
    {'keyword': '望石智慧', 'weight': 10},
    {'keyword': '费米子', 'weight': 10},
    {'keyword': '焕一生物', 'weight': 10},
    {'keyword': '中以海德', 'weight': 10},
    {'keyword': '碳硅智慧', 'weight': 10},
    {'keyword': 'PandaOmics', 'weight': 10},
    {'keyword': 'RoseTTAFold', 'weight': 10},
    {'keyword': 'DeepGO', 'weight': 10},
    {'keyword': 'DeepGOPlus', 'weight': 10},
    {'keyword': 'trRosetta', 'weight': 10},
    {'keyword': 'ProteinMPNN', 'weight': 10},
    {'keyword': 'RFDiffusion', 'weight': 10},
    {'keyword': 'ProGen', 'weight': 10},
    {'keyword': 'AlphaFold-Multimer', 'weight': 10},
    {'keyword': 'EquiDock', 'weight': 10},
    {'keyword': 'EquiBind', 'weight': 10},
    {'keyword': 'DeepTrio', 'weight': 10},
    {'keyword': 'UniFold', 'weight': 10},
    {'keyword': 'TANKBind', 'weight': 10},
    {'keyword': 'DIFFDOCK', 'weight': 10},
    {'keyword': 'DIFFDOCK-PP', 'weight': 10},
    {'keyword': 'HIGH-PPI', 'weight': 10},
    {'keyword': 'RoseTTAFold2NA', 'weight': 10},
    {'keyword': 'DNN-PPI', 'weight': 10},
    {'keyword': 'NUVO', 'weight': 10},
    {'keyword': 'PocketExpander', 'weight': 10},
    {'keyword': 'MolGen', 'weight': 10},
    {'keyword': 'GEMS', 'weight': 10},
    {'keyword': 'ReSOLVE', 'weight': 10},
    {'keyword': 'DragonFold', 'weight': 10},
    {'keyword': 'Kinetic Ensemble', 'weight': 10},
    {'keyword': 'EnsemNET', 'weight': 10},
    {'keyword': 'EnsemGEN', 'weight': 10},
    {'keyword': 'ACE平台', 'weight': 10},
    {'keyword': 'ALLOSTAR', 'weight': 10},
    {'keyword': 'GlycoVision', 'weight': 10},
    {'keyword': 'Proteonano', 'weight': 10},
    {'keyword': 'Intelligent Protein', 'weight': 10},
    {'keyword': 'ASCEND', 'weight': 10},
    {'keyword': 'Chroma', 'weight': 10},
    {'keyword': 'AbMap', 'weight': 10},
    {'keyword': 'IMPACT', 'weight': 10},
    {'keyword': 'Helixon', 'weight': 10},
    {'keyword': 'AbZed', 'weight': 10},
    {'keyword': 'SynCore', 'weight': 10},
    {'keyword': 'Divamics', 'weight': 10},
    {'keyword': 'SPOTLIGHT', 'weight': 10},
    {'keyword': 'HYPERFOCUS', 'weight': 10},
    {'keyword': 'CRYO-CADD', 'weight': 10},
    {'keyword': 'LucCage', 'weight': 10},
    {'keyword': 'LuxSit', 'weight': 10},
    {'keyword': 'ZCloud', 'weight': 10},
    {'keyword': 'Lesign', 'weight': 10},
    {'keyword': 'MoleculeOS', 'weight': 10},
    {'keyword': 'DeepCure', 'weight': 10},
    {'keyword': 'BenchSci', 'weight': 10},
    {'keyword': 'Redesign Science', 'weight': 10},
    {'keyword': 'Anthropic', 'weight': 10},
    {'keyword': 'ABSci', 'weight': 10},
    {'keyword': 'AbCellera', 'weight': 10},
    {'keyword': 'LabGenius', 'weight': 10}
]


# Topic = 先锋热点
HotPoint_keywords = [
    {'keyword': '马斯克', 'weight': 10},
    {'keyword': 'elon musk', 'weight': 10},
    {'keyword': '马云', 'weight': 10},
    {'keyword': 'p70', 'weight': 10},
    {'keyword': '董宇辉', 'weight': 10},
    {'keyword': '与辉同行', 'weight': 10},
    {'keyword': '人形机器人', 'weight': 10},
    {'keyword': '固态电池', 'weight': 10},
    {'keyword': '小米汽车', 'weight': 10},
    {'keyword': 'su7', 'weight': 10},
    {'keyword': 'su 7', 'weight': 10},
    {'keyword': 'su8', 'weight': 10},
    {'keyword': 'su 8', 'weight': 10},
    {'keyword': '小米suv', 'weight': 10},
    {'keyword': '雷军', 'weight': 9},
    {'keyword': '雷总', 'weight': 9},

]

# Topic = AI算力
AIHPC_keywords = [
    # AI概念
    {'keyword': 'AGI', 'weight': 10},
    # {'keyword': 'ASI', 'weight': 10},
    # AI公司产品人物
    {'keyword': 'openai', 'weight': 10},
    {'keyword': 'gpt5', 'weight': 10},
    {'keyword': 'gpt 5', 'weight': 10},
    {'keyword': 'gpt-5', 'weight': 10},
    {'keyword': 'gpt4.5', 'weight': 10},
    {'keyword': 'gpt 4.5', 'weight': 10},
    {'keyword': 'gpt-4.5', 'weight': 10},
    {'keyword': 'Ilya', 'weight': 10},
    {'keyword': 'Sam Altman', 'weight': 10},
    {'keyword': '山姆·奥特曼', 'weight': 10},
    {'keyword': 'kimi', 'weight': 10},
    {'keyword': 'chatglm', 'weight': 10},
    {'keyword': 'sora', 'weight': 10},

    # 算力芯片
    {'keyword': '算力芯片', 'weight': 10},
    {'keyword': 'AI芯片', 'weight': 10},
    {'keyword': 'nv', 'weight': 10},
    {'keyword': 'nvida', 'weight': 10},
    {'keyword': '黄仁勋', 'weight': 10},
    {'keyword': 'A100', 'weight': 10},
    {'keyword': 'B200', 'weight': 10},
    {'keyword': 'tpu', 'weight': 10},
    {'keyword': 'AI加速卡', 'weight': 10},
    {'keyword': 'Marvell', 'weight': 10},

    # 算通一体化
    {'keyword': 'NVLink', 'weight': 10},
    {'keyword': '硅光', 'weight': 10},
    {'keyword': 'silicon photonic', 'weight': 10},
    {'keyword': '光互联', 'weight': 10},
    {'keyword': 'optical interconnects', 'weight': 10},
    {'keyword': 'optical interconnect', 'weight': 10},
    {'keyword': 'interconnect', 'weight': 10},
    {'keyword': 'HB domain', 'weight': 10},
    {'keyword': 'AI Factory', 'weight': 10},
    {'keyword': 'CPO', 'weight': 10},
    {'keyword': 'OCS', 'weight': 10},
    {'keyword': 'CXL', 'weight': 10},
    {'keyword': 'compute express link', 'weight': 10},
    {'keyword': 'ayar', 'weight': 10},
]

# Topic = Lidar智驾
LidarADAS_keywords = [
    {'keyword': '激光雷达', 'weight': 10},
    {'keyword': 'Lidar', 'weight': 10},
    {'keyword': 'FMCW', 'weight': 10},
    {'keyword': 'OPA', 'weight': 10},
    {'keyword': '智驾', 'weight': 10},
    {'keyword': '禾赛', 'weight': 10},
    {'keyword': '速腾聚创', 'weight': 10},
    {'keyword': '图达通', 'weight': 10},
    {'keyword': '华为激光雷达', 'weight': 10},
    {'keyword': '镭神', 'weight': 10},
    {'keyword': '一径科技', 'weight': 10},
    {'keyword': '大疆览沃', 'weight': 10},
    {'keyword': '北醒', 'weight': 10},
    {'keyword': '探维', 'weight': 10},
    {'keyword': '洛微', 'weight': 10},
    {'keyword': '摩尔芯光', 'weight': 10},
    {'keyword': '万集科技', 'weight': 10},
    {'keyword': '炬光科技', 'weight': 10},
    {'keyword': '长光华芯', 'weight': 10},
    {'keyword': '芯视界', 'weight': 10},
    {'keyword': '阜时', 'weight': 10},
    {'keyword': '识光', 'weight': 10},
    {'keyword': '纵慧芯光', 'weight': 10},
    {'keyword': '奥比中光', 'weight': 10},
    {'keyword': '永新光学', 'weight': 10},
    {'keyword': '蓝特光学', 'weight': 10},
    {'keyword': 'Luminar', 'weight': 10},
    {'keyword': 'Aeva', 'weight': 10},
    {'keyword': 'Ouster', 'weight': 10},
    {'keyword': '奥锐达', 'weight': 10},
    {'keyword': '天眸光电', 'weight': 10},
    {'keyword': '北科天绘', 'weight': 10},
    {'keyword': '激光雷达研报', 'weight': 10},
    {'keyword': '激光雷达深度报告', 'weight': 10},
    {'keyword': '激光雷达研究报告', 'weight': 10},
    {'keyword': '激光雷达行业报告', 'weight': 10},
    {'keyword': '毫米波雷达研报', 'weight': 10},
    {'keyword': '毫米波雷达深度报告', 'weight': 10},
    {'keyword': '毫米波雷达研究报告', 'weight': 10},
    {'keyword': '毫米波雷达行业报告', 'weight': 10},
    {'keyword': '智能网联', 'weight': 10},
    {'keyword': '车路协同', 'weight': 10},
    {'keyword': 'V2X', 'weight': 10},
    {'keyword': '无人配送', 'weight': 10},
    {'keyword': '无人物流', 'weight': 10},
    {'keyword': 'Robobus', 'weight': 10},
    {'keyword': 'Robotaxi', 'weight': 10},
    {'keyword': '无人货车', 'weight': 10},
    {'keyword': 'Robotruck', 'weight': 10},
    {'keyword': '新石器无人车', 'weight': 10},
    {'keyword': '美团无人车', 'weight': 10},
    {'keyword': '阿里小蛮驴无人车', 'weight': 10},
    {'keyword': '京东无人车', 'weight': 10},
    {'keyword': '百度Robotaxi', 'weight': 10},
    {'keyword': '萝卜快跑', 'weight': 10},
    {'keyword': '滴滴自动驾驶', 'weight': 10},
    {'keyword': '智加科技', 'weight': 10},
    {'keyword': '禾多科技', 'weight': 10},
    {'keyword': 'Momenta', 'weight': 10},
    {'keyword': '文远知行', 'weight': 10},
    {'keyword': '小马智行', 'weight': 10},
    {'keyword': '元戎启行', 'weight': 10},
]

# Topic = 量化
quantitative_trading_keywords = [
    {'keyword': '量化', 'weight': 10},
    {'keyword': '程序化交易', 'weight': 10},
    {'keyword': '对冲基金', 'weight': 10},
    {'keyword': '量化私募', 'weight': 10},
    {'keyword': '量化基金', 'weight': 10},
    {'keyword': '量化交易', 'weight': 10},
    {'keyword': '算法交易', 'weight': 10},
    {'keyword': '转融通', 'weight': 10},
    {'keyword': '阿尔法', 'weight': 9},
    {'keyword': '阿尔法值', 'weight': 9},
    {'keyword': '阿尔法收益', 'weight': 9},
    {'keyword': '贝塔收益', 'weight': 7},
    {'keyword': '贝塔', 'weight': 9},
    {'keyword': 'beta', 'weight': 9},
    {'keyword': 'beta值', 'weight': 9},
    {'keyword': 'beta收益', 'weight': 7},
    {'keyword': '超额收益', 'weight': 8},
    {'keyword': '超额回报', 'weight': 8},
    {'keyword': '择时策略', 'weight': 8},
    {'keyword': '择时', 'weight': 8},
    {'keyword': 'dma策略', 'weight': 10},
    {'keyword': 'dma', 'weight': 10},
    {'keyword': 'dma交易', 'weight': 10},
    {'keyword': '高频交易', 'weight': 10},
    {'keyword': '高频', 'weight': 9},
    {'keyword': '高频策略', 'weight': 9},
    {'keyword': '对冲策略', 'weight': 9},
    {'keyword': '量化对冲', 'weight': 10},
    {'keyword': '多空策略', 'weight': 8},
    {'keyword': '股指策略', 'weight': 8},
    {'keyword': '股票多空', 'weight': 7},
    {'keyword': 'cta', 'weight': 9},
    {'keyword': 'cta策略', 'weight': 9},
    {'keyword': '指增', 'weight': 10},
    {'keyword': 'smart beta', 'weight': 10},
    {'keyword': 'smart贝塔', 'weight': 10},
    {'keyword': 'smart β', 'weight': 10},
    {'keyword': '风格切换', 'weight': 8},
    {'keyword': 'etf套利', 'weight': 10},
    {'keyword': '宽基', 'weight': 10},
    {'keyword': '跨品种套利', 'weight': 8},
    {'keyword': '事件驱动', 'weight': 7},
    {'keyword': '事件驱动策略', 'weight': 8},
    {'keyword': '统计套利', 'weight': 9},
    {'keyword': '统计学', 'weight': 5},
    {'keyword': '统计学策略', 'weight': 7},
    {'keyword': '风格投资', 'weight': 6},
    {'keyword': '因子策略', 'weight': 10},
    {'keyword': '因子挖掘', 'weight': 10},
    {'keyword': '量化选股', 'weight': 8},
    {'keyword': '基本面选股', 'weight': 5},
    {'keyword': '量化择时', 'weight': 8},
    {'keyword': '蒙特卡罗模拟', 'weight': 7},
    {'keyword': '生成对抗网络', 'weight': 5},
    {'keyword': '指数增强', 'weight': 6},
    {'keyword': '动量策略', 'weight': 8},
    {'keyword': '均值回复', 'weight': 7},
    {'keyword': '均值回复策略', 'weight': 8},
    {'keyword': '基本面量化', 'weight': 8},
    {'keyword': '基本面量化策略', 'weight': 9},
    {'keyword': '技术分析策略', 'weight': 8},
    {'keyword': '市场中性', 'weight': 7},
    {'keyword': '市场中性策略', 'weight': 8},
    {'keyword': '趋向跟踪', 'weight': 7},
    {'keyword': '趋向跟踪策略', 'weight': 8},
    {'keyword': '投机策略', 'weight': 6},
    {'keyword': '指数化投资', 'weight': 5},
    {'keyword': '进化算法优化', 'weight': 7},
    {'keyword': '张量计算', 'weight': 4},
    {'keyword': '期现套利', 'weight': 9},
    {'keyword': '商品期货', 'weight': 8},
    {'keyword': '调仓策略', 'weight': 7},
    {'keyword': '回撤管理', 'weight': 9},
    {'keyword': '市场冲击', 'weight': 8},
    {'keyword': '冲击成本', 'weight': 7},
    {'keyword': '最大回撤', 'weight': 8},
    {'keyword': 'drawdown', 'weight': 10},
    {'keyword': '夏普', 'weight': 10},
    {'keyword': '风险收益比', 'weight': 9},
    {'keyword': '波动率曲面', 'weight': 8},
    {'keyword': '隐含波动率', 'weight': 8},
    {'keyword': 'asset allocation', 'weight': 8},
    {'keyword': '赎回', 'weight': 4},
    {'keyword': '赎回费', 'weight': 4},
    {'keyword': 'redemption fee', 'weight': 4},
    {'keyword': '微盘股', 'weight': 3},
    {'keyword': 'cta', 'weight': 9},
    {'keyword': '多空策略', 'weight': 7},
    {'keyword': '风险平价', 'weight': 8},
    {'keyword': '风险平价策略', 'weight': 9},
    {'keyword': '证券组合优化', 'weight': 9},
    {'keyword': '均值方差模型', 'weight': 8},
    {'keyword': '结构化产品', 'weight': 6},
    # {'keyword': '期权投资组合', 'weight': 9},
    # {'keyword': '市场收益率', 'weight': 9},
    # {'keyword': 'market return', 'weight': 9},
    # {'keyword': '市场效率', 'weight': 9},
    # {'keyword': '有效市场', 'weight': 8},
    # {'keyword': 'market efficiency', 'weight': 9},
    # {'keyword': 'capital flow', 'weight': 8},
    # {'keyword': '投资者情绪', 'weight': 6},
    # {'keyword': 'sentiment', 'weight': 6},
    {'keyword': '回测', 'weight': 10},
    {'keyword': '实盘', 'weight': 10},
    # {'keyword': 'strategy backtesting', 'weight': 10},
    # {'keyword': '策略绩效评估', 'weight': 10},
    # {'keyword': 'strategy performance evaluation', 'weight': 10},
    # {'keyword': '波浪理论', 'weight': 6},
    # {'keyword': '能量潮理论', 'weight': 5},
    # {'keyword': '分型分析', 'weight': 6},
    # {'keyword': '分型理论', 'weight': 6},
    # {'keyword': '压力支撑位', 'weight': 6},
    # {'keyword': '突破形态', 'weight': 7},
    # {'keyword': 'sar', 'weight': 5},
    # {'keyword': 'sar指标', 'weight': 6},
    # {'keyword': 'atr指标', 'weight': 6},
    # {'keyword': 'atr', 'weight': 6},
    # {'keyword': 'vr指标', 'weight': 5},
    # {'keyword': 'vr', 'weight': 5},
    # {'keyword': 'dmi指标', 'weight': 6},
    # {'keyword': 'dmi', 'weight': 6},
    # {'keyword': 'cci指标', 'weight': 6},
    # {'keyword': 'cci', 'weight': 6},
    # {'keyword': 'kdj指标', 'weight': 6},
    # {'keyword': 'kdj', 'weight': 6},
    # {'keyword': 'vstop指标', 'weight': 5},
    # {'keyword': 'vstop', 'weight': 5},
    # {'keyword': 'boll指标', 'weight': 6},
    # {'keyword': 'boll', 'weight': 6},
    # {'keyword': 'rsi指标', 'weight': 7},
    # {'keyword': 'rsi', 'weight': 7},
    # {'keyword': '胜率', 'weight': 8},
    {'keyword': '索提诺比率', 'weight': 7},
    {'keyword': '贝塔系数', 'weight': 8},
    {'keyword': '阿尔法系数', 'weight': 8},
    {'keyword': '波动率曲面', 'weight': 9},
    {'keyword': '隐含波动率', 'weight': 9},
    {'keyword': '风险值', 'weight': 9},
    {'keyword': '希腊值', 'weight': 9},
    {'keyword': '套利定价', 'weight': 9},
    {'keyword': '有效市场假说', 'weight': 8},
    {'keyword': '互换', 'weight': 8},
    {'keyword': '股指期货', 'weight': 8},
    {'keyword': '赢率', 'weight': 8},
    {'keyword': '索提诺比率', 'weight': 7},
    {'keyword': 'beta值', 'weight': 8},
    {'keyword': 'alpha', 'weight': 9},
    {'keyword': '波率曲面', 'weight': 9},
    {'keyword': '希腊值', 'weight': 9},
    {'keyword': '无风险套利', 'weight': 10},
    {'keyword': '市场有效', 'weight': 9},
    {'keyword': '协整分析', 'weight': 8},
    {'keyword': '分位数跟踪', 'weight': 8},
    {'keyword': '期权定价', 'weight': 10},
    {'keyword': '套利策略', 'weight': 10},
    {'keyword': '幻方', 'weight': 10},
    {'keyword': '明汯', 'weight': 10},
    {'keyword': '灵均', 'weight': 10},
    {'keyword': '九坤', 'weight': 10},
    {'keyword': '衍复', 'weight': 10},
    {'keyword': '天演', 'weight': 10},
    {'keyword': '卓识', 'weight': 10},
    {'keyword': '稳博', 'weight': 10},
    {'keyword': '宽德', 'weight': 10},
    {'keyword': '世纪前沿', 'weight': 10},
    {'keyword': '诚奇', 'weight': 10},
    {'keyword': '金锝', 'weight': 10},
    {'keyword': '启林', 'weight': 10},
    {'keyword': '茂源量化', 'weight': 10},
    {'keyword': '金戈量锐', 'weight': 10},
    {'keyword': '黑翼', 'weight': 10},
    {'keyword': '信弘天禾', 'weight': 10},
    {'keyword': '思勰', 'weight': 10},
    {'keyword': '呜石', 'weight': 10},
    {'keyword': '锐天', 'weight': 10},
    {'keyword': '龙旗科技', 'weight': 10},
    {'keyword': '进化论', 'weight': 10},
    {'keyword': '宽产', 'weight': 10},
    {'keyword': '博普', 'weight': 10},
    {'keyword': '赫富', 'weight': 10},
    {'keyword': '涵德', 'weight': 10},
    {'keyword': '国恩', 'weight': 10},
    {'keyword': '艾方', 'weight': 10},
    {'keyword': '星瑞', 'weight': 10},
    {'keyword': '白鹭', 'weight': 10},
    {'keyword': '因诺', 'weight': 10},
    {'keyword': '凯纳', 'weight': 10},
    {'keyword': '念空念觉', 'weight': 10},
    {'keyword': '千象', 'weight': 10},
    {'keyword': '洛书', 'weight': 10},
    {'keyword': '蒙玺', 'weight': 10},
    {'keyword': '千宜', 'weight': 10},
    {'keyword': '平方和', 'weight': 10},
    {'keyword': '申毅', 'weight': 10},
    {'keyword': '心汉页习', 'weight': 10},
    {'keyword': '乾象', 'weight': 10},
    {'keyword': '盛冠达', 'weight': 10},
    {'keyword': '思晔', 'weight': 10},
    {'keyword': '天算量化', 'weight': 10},
    {'keyword': '图灵量化', 'weight': 10},
    {'keyword': '衍盛', 'weight': 10},
    {'keyword': '象限', 'weight': 10},
    {'keyword': '展弘', 'weight': 10},
    {'keyword': '仲阳天王', 'weight': 10},
    {'keyword': '顽岩', 'weight': 10},
    {'keyword': '致诚卓远', 'weight': 10},
    {'keyword': '磐松', 'weight': 10},
]